import type { KpiDefinition } from "../domain/types";

const V = "2026-01";

export const KPI_DEFINITIONS: KpiDefinition[] = [
  // ── FRONT OFFICE ──────────────────────────────────────────────────────────
  {
    kpiDefId: "fo_guest_experience",
    departmentId: "front_office",
    name: "Guest Experience",
    nameAr: "تجربة الضيف",
    weight: 0.20,
    maxScore: 100,
    scoringMethod: "weightedQuestionnaire",
    params: {
      yes: 20,
      partial: 10,
      no: 0,
      overallWeight: 20,
      cap: 100,
    },
    active: true,
    configVersion: V,
  },
  {
    kpiDefId: "fo_supervisor",
    departmentId: "front_office",
    name: "Supervisor",
    nameAr: "تقييم المشرف",
    weight: 0.15,
    maxScore: 110,
    scoringMethod: "weightedQuestionnaire",
    params: {
      yes: 16,
      partial: 8,
      no: 0,
      overallWeight: 20,
      cap: 110,
      bonus: 10,
    },
    active: true,
    configVersion: V,
  },
  {
    kpiDefId: "fo_attendance",
    departmentId: "front_office",
    name: "Attendance",
    nameAr: "الحضور",
    weight: 0.20,
    maxScore: 100,
    scoringMethod: "deduction",
    params: {
      base: 100,
      floor: 0,
      penalties: [
        { field: "absentDays", factor: 8 },
        { field: "lateMinutes", factor: 0.3 },
      ],
    },
    active: true,
    configVersion: V,
  },
  {
    kpiDefId: "fo_upselling",
    departmentId: "front_office",
    name: "Upselling",
    nameAr: "المبيعات الإضافية",
    weight: 0.15,
    maxScore: 100,
    scoringMethod: "ratioVsTarget",
    params: { cap: 100 },
    active: true,
    configVersion: V,
  },
  {
    kpiDefId: "fo_enrollments",
    departmentId: "front_office",
    name: "Enrollments",
    nameAr: "تسجيل الولاء",
    weight: 0.15,
    maxScore: 120,
    scoringMethod: "ratioVsTarget",
    params: { cap: 120 },
    active: true,
    configVersion: V,
  },
  {
    kpiDefId: "fo_production",
    departmentId: "front_office",
    name: "Production",
    nameAr: "الإنتاجية",
    weight: 0.15,
    maxScore: 100,
    scoringMethod: "sumDivided",
    params: {
      fields: ["checkIns", "checkOuts", "transactions"],
      divisor: 4.0,
      cap: 100,
    },
    active: true,
    configVersion: V,
  },

  // ── HOUSEKEEPING ───────────────────────────────────────────────────────────
  {
    kpiDefId: "hk_room_quality",
    departmentId: "housekeeping",
    name: "Room Quality",
    nameAr: "جودة الغرف",
    weight: 0.35,
    maxScore: 100,
    scoringMethod: "passthrough",
    params: {},
    active: true,
    configVersion: V,
  },
  {
    kpiDefId: "hk_productivity",
    departmentId: "housekeeping",
    name: "Productivity",
    nameAr: "الإنتاجية",
    weight: 0.30,
    maxScore: 100,
    scoringMethod: "ratioVsTarget",
    params: { cap: 100 },
    active: true,
    configVersion: V,
  },
  {
    kpiDefId: "hk_attendance",
    departmentId: "housekeeping",
    name: "Attendance",
    nameAr: "الحضور",
    weight: 0.20,
    maxScore: 100,
    scoringMethod: "deduction",
    params: {
      base: 100,
      floor: 0,
      penalties: [
        { field: "absentDays", factor: 8 },
        { field: "lateMinutes", factor: 0.3 },
      ],
    },
    active: true,
    configVersion: V,
  },
  {
    kpiDefId: "hk_supervisor",
    departmentId: "housekeeping",
    name: "Supervisor",
    nameAr: "تقييم المشرف",
    weight: 0.15,
    maxScore: 100,
    scoringMethod: "weightedQuestionnaire",
    params: {
      yes: 16,
      partial: 8,
      no: 0,
      overallWeight: 20,
      cap: 100,
    },
    active: true,
    configVersion: V,
  },
];
