/* ── strings.js — EN/AR string table (LANGUAGE.md) ──────────────────────────
   One flat, key-based table per LANGUAGE.md §6. No hardcoded UI literal
   should be left in a view file — every user-facing string looks itself up
   here via t("dotted.key") at RENDER time (not baked into a const at module
   load, so a language toggle re-renders with the new text immediately).

   Language state is a small module-level store + subscriber set (NOT a React
   Context) — this app deliberately avoids Context per PERFORMANCE.md's fat-
   ctx re-render note and Night_Audit_Final_Status.md's own call not to
   refactor toward one. Any component that needs to re-render on a language
   change calls useLang() once; t()/tHelp() read the current language
   directly, so nested helpers/callbacks never need it threaded through.

   Anonymous screens (IdentityGate, pre-identify) follow the device's last-
   used language (persisted to localStorage here). After PIN identify, the
   staff registry's own `language` field takes over (app.js applies it via
   setLang() in a useEffect keyed on identity.currentEntry). ─────────────── */

const LANG_KEY="na_lang";
let currentLang=(function(){
  try{const saved=localStorage.getItem(LANG_KEY);if(saved==="en"||saved==="ar")return saved;}catch{}
  return "en";
})();
const langListeners=new Set();
function getLang(){return currentLang;}
function setLang(lang){
  if(lang!=="en"&&lang!=="ar")return;
  if(lang===currentLang)return;
  currentLang=lang;
  try{localStorage.setItem(LANG_KEY,lang);}catch{}
  langListeners.forEach(fn=>{try{fn(lang);}catch{}});
}
function useLang(){
  const[lang,setLangState]=useState(currentLang);
  useEffect(()=>{
    const fn=l=>setLangState(l);
    langListeners.add(fn);
    return()=>langListeners.delete(fn);
  },[]);
  return lang;
}
function tGet(obj,path){
  return path.split(".").reduce((o,k)=>(o&&o[k]!=null?o[k]:undefined),obj);
}
/* t("a.b.c", arg0, arg1, ...) — {0}/{1}/… placeholders substituted in order. */
function t(key,...args){
  let s=tGet(STRINGS[currentLang],key);
  if(s==null)s=tGet(STRINGS.en,key);
  if(s==null)return key;
  let out=String(s);
  args.forEach((a,i)=>{out=out.split("{"+i+"}").join(a);});
  return out;
}
function tHelp(view){
  return (HELP_STRINGS[currentLang]||HELP_STRINGS.en)[view]||[];
}
/* Simple two-way count form for English ("s" suffix) — used inline at call
   sites, not part of the table. Arabic business UI commonly uses the plural/
   collective noun form alongside the numeral regardless of exact count
   (dual/plural agreement is not attempted here — flagged in STATUS as a
   simplification, not a grammar-perfect implementation). */
function plural(n,one,many){return n===1?one:many;}
/* English-only "s" pluralization suffix, used as the {1}/{2} arg in several
   table keys (e.g. "{0} new row{1}") — resolves to "" in Arabic, since the
   Arabic templates carry their own count-invariant plural noun instead of an
   appended letter (see strings.js header on the plural-form simplification). */
function pluralSuffix(n){return currentLang==="en"?(n===1?"":"s"):"";}
/* auditStatus/h.status values ("Draft"/"Submitted for Review"/"Approved")
   are the STORED enum (RECORDS.md envelopes, STATUSES in constants.js) —
   never renamed, only display-mapped here so every badge that shows one
   translates without touching saved data. */
function statusLabel(s){
  if(s==="Closed")return t("status.closed");
  if(s==="Approved")return t("status.approved");
  if(s==="Submitted for Review")return t("status.submitted");
  return t("status.draft");
}
/* PLO_TYPES (constants.js) stays the stored English enum (checks[].ploType,
   saved-record/export data) — this maps it to a display label only, same
   pattern as statusLabel/cashStatusLabel above. */
function ploTypeLabel(pt){
  if(pt==="Payment Link")return t("plo.typePaymentLink");
  if(pt==="Laundry")return t("plo.typeLaundry");
  return t("plo.typeOther");
}

/* ── HELP_STRINGS — per-view instruction bullets (constants.js's old
   HELP_TEXT, now looked up live via tHelp() instead of a load-time const). ── */
const HELP_STRINGS={
  en:{
    upload:[
      "Export the cashier journal from Opera for the business date you're auditing, as .xlsx, and drop it here.",
      "Check that the date shown matches the export before continuing.",
      "If a second batch comes in late for the same night, use Re-sync from the Journal view to merge it in — don't re-upload from scratch, that loses your checks/flags."],
    journal:[
      "Every transaction is grouped by cashier. Click the checkbox or press C / Space to check a row; press F to flag it and leave a note.",
      "Use ↑ / ↓ to move between rows, Tab to jump to the next unchecked one, and 1–9 to filter (All, Unchecked, Payments, Charges, Cards, Cash, Corrections, PLO, New).",
      "If something needs correcting, flag it and link it to its reversal/replacement so both sides show in the audit trail.",
      "A flagged row left unlinked stays open — you'll need to acknowledge it before final approval."],
    cash:[
      "Enter what was physically counted in the drawer for each cashier.",
      "The variance against Opera's cash total is colored by how far off it is, not a single pass/fail cutoff — small amounts are normal handling slack."],
    reconcile:[
      "Machine Z-Reports: enter the amount and transaction count from each terminal's paper Z-report, per card type. Tab walks down one machine's card types before moving to the next, so you can fill in one paper slip at a time.",
      "PLO Entries: tag any card payment that was actually a Paid-Out so it's correctly excluded from the discrepancy.",
      "The Discrepancy Summary shows amount and count mismatches separately — a count mismatch can hide behind a matching amount if two wrong entries cancel out.",
      "Cash per Cashier and Non-Card Settlements complete the reconciliation — count physical cash on the Cash tab for every cashier; City Ledger/ALL Reward/Expedia are listed for a complete total, since there's no terminal to check them against.",
      "Submit for review, then the Night Manager approves. Unchecked rows block approval; an open flag just needs to be acknowledged."],
    reports:[
      "Generates the final PDF — a summary page plus the full per-cashier journal, including charges and tax lines.",
      "Available for Draft or Approved audits; exported PDFs are watermarked DRAFT until the audit is approved."],
    history:[
      "Every approved audit is saved here automatically, with per-agent cash and correction trends over time.",
      "This is a saved record, separate from your live data — reopening a past date here doesn't load it back into the Journal for editing."],
    production:[
      "Journal transactions and corrections come from your saved Audit History automatically — no upload needed for that part.",
      "Upload the Opera user_activity_log XML export for check-ins/check-outs; if it's filtered to one action type, upload the others separately, they merge.",
      "Map each cashier ID and Opera username to a staff ID below — unmapped identities are excluded from scoring until mapped.",
      "Weights are editable and apply immediately; save a month once its data is complete to write the record to your connected folder."],
    staffPins:[
      "PINs identify who is acting — they are attribution, not a second password. The shared staff list and PINs are the same ones used by every PMS app.",
      "Connect the shared PMS folder here so PINs and roles stay in sync with Guest Care and the other apps.",
      "Only a Night Manager or top admin can grant roles, reset most PINs, or edit the permissions matrix. Anyone can reset their own PIN."],
    activity:[
      "Every identify, PIN change, role grant, submit/sign-off and save is logged here automatically — nothing can be deleted or edited.",
      "This device's list is capped for display; the full history is written to Records/Night Audit/activity-log/ on the connected PMS folder."]
  },
  ar:{
    upload:[
      "صدّر دفتر يومية الكاشير من أوبرا لتاريخ العمل الذي تراجعه، بصيغة .xlsx، واسحبه هنا.",
      "تأكد أن التاريخ الظاهر يطابق الملف المُصدَّر قبل المتابعة.",
      "إذا وصلت دفعة ثانية متأخرة لنفس الليلة، استخدم إعادة المزامنة من شاشة اليومية لدمجها — لا تُعِد الرفع من الصفر، فذلك يفقد التحقق والإشارات التي أدخلتها."],
    journal:[
      "كل معاملة مصنّفة حسب الكاشير. انقر على المربع أو اضغط C أو مسافة للتحقق من الصف؛ اضغط F لوضع إشارة وترك ملاحظة.",
      "استخدم ↑ / ↓ للتنقل بين الصفوف، Tab للانتقال إلى أول صف غير محقَّق، والأرقام 1–9 للتصفية (الكل، غير محقَّق، مدفوعات، رسوم، بطاقات، نقدي، تصحيحات، PLO، جديد).",
      "إذا احتاجت معاملة تصحيحاً، ضع عليها إشارة واربطها بمعاملة العكس/الاستبدال ليظهر الطرفان في مسار التدقيق.",
      "الصف الذي عليه إشارة ولم يُربط يبقى مفتوحاً — يجب الإقرار به قبل الاعتماد النهائي."],
    cash:[
      "أدخل المبلغ الذي تم عدّه فعلياً في الدرج لكل كاشير.",
      "يُلوَّن الفارق مقابل إجمالي أوبرا النقدي حسب مقدار الفرق، وليس بمعيار نجاح/فشل واحد — الفروقات الصغيرة تُعد تفاوتاً طبيعياً في التعامل النقدي."],
    reconcile:[
      "تقارير إغلاق الأجهزة (Z-Report): أدخل المبلغ وعدد المعاملات من تقرير الإغلاق الورقي لكل جهاز، لكل نوع بطاقة. يتنقل مفتاح Tab عبر أنواع البطاقات لجهاز واحد قبل الانتقال للجهاز التالي، لتُدخل بيانات كشف ورقي واحد في كل مرة.",
      "إدخالات PLO: ضع إشارة على أي دفعة بطاقة كانت في الحقيقة صرفاً (Paid-Out) ليتم استبعادها بشكل صحيح من الفارق.",
      "ملخص الفارق يعرض فروقات المبلغ والعدد بشكل منفصل — قد يختفي فارق في العدد خلف مبلغ متطابق إذا ألغى إدخالان خاطئان بعضهما.",
      "«النقدية حسب الكاشير» و«تسويات بدون بطاقة» تُكمل المطابقة — عُدّ النقدية فعلياً في تبويب النقدي لكل كاشير؛ أما City Ledger وALL Reward وExpedia فتُعرض لإظهار إجمالي كامل، لعدم وجود جهاز طرفي لمطابقتها.",
      "أرسل للمراجعة، ثم يعتمدها مدير المناوبة الليلية. الصفوف غير المحقَّقة تمنع الاعتماد؛ الإشارة المفتوحة تحتاج فقط للإقرار بها."],
    reports:[
      "يُنشئ ملف PDF النهائي — صفحة ملخص إضافة إلى يومية كل كاشير كاملة، شاملة الرسوم وبنود الضريبة.",
      "متاح للتدقيق في حالة مسودة أو معتمد؛ ملفات PDF المُصدَّرة تحمل علامة مسودة حتى يُعتمد التدقيق."],
    history:[
      "كل تدقيق معتمد يُحفظ هنا تلقائياً، مع اتجاهات النقدية والتصحيحات لكل موظف عبر الوقت.",
      "هذا سجل محفوظ، منفصل عن بياناتك الحية — إعادة فتح تاريخ سابق هنا لا يُحمّله مرة أخرى في اليومية للتعديل."],
    production:[
      "معاملات اليومية والتصحيحات تأتي تلقائياً من أرشيف التدقيق المحفوظ لديك — لا حاجة لرفع ملف لهذا الجزء.",
      "ارفع ملف XML الخاص بسجل نشاط المستخدمين (user_activity_log) من أوبرا لتسجيل الوصول/المغادرة؛ إذا كان مُصفّى لنوع إجراء واحد، ارفع البقية بشكل منفصل، وسيتم دمجها.",
      "اربط كل رقم كاشير واسم مستخدم أوبرا برقم موظف أدناه — الهويات غير المربوطة تُستبعد من الاحتساب حتى تُربط.",
      "الأوزان قابلة للتعديل وتُطبَّق فوراً؛ احفظ الأسبوع بعد اكتمال بياناته لكتابة السجل في المجلد المتصل."],
    staffPins:[
      "الرموز التعريفية (PIN) تُحدّد من يقوم بالإجراء — وهي وسيلة نسب وليست كلمة مرور ثانية. قائمة الموظفين والرموز مشتركة مع كل تطبيقات النظام.",
      "اربط مجلد النظام المشترك هنا ليبقى الرمز التعريفي والصلاحيات متزامنة مع رعاية النزلاء والتطبيقات الأخرى.",
      "فقط مدير المناوبة الليلية أو مدير النظام يمكنه منح الصلاحيات، أو إعادة تعيين معظم الرموز، أو تعديل جدول الصلاحيات. أي شخص يمكنه إعادة تعيين رمزه الخاص."],
    activity:[
      "كل تسجيل دخول، وتغيير رمز، ومنح صلاحية، وإرسال/اعتماد، وحفظ يُسجَّل هنا تلقائياً — لا يمكن حذف أو تعديل أي سجل.",
      "قائمة هذا الجهاز محدودة للعرض؛ السجل الكامل يُكتب في Records/Night Audit/activity-log/ داخل مجلد النظام المتصل."]
  }
};

const STRINGS={
en:{
  common:{
    sar:"SAR", cancel:"Cancel", save:"Save", close:"Close", loading:"Loading…",
    yes:"Yes", no:"No", edit:"Edit", clear:"Clear", assign:"Assign", refresh:"Refresh",
    connect:"Connect", reconnect:"Reconnect", back:"Back", collapse:"Collapse",
    balanced:"✓ Balanced", discrepancy:"Discrepancy", pending:"Pending", status:"Status",
    total:"Total", date:"Date", time:"Time", room:"Room", guest:"Guest", agent:"Agent",
    dash:"–", none:"None", delayed:"delayed", delayedDays:"delayed · {0} day{1}"
  },
  nav:{
    upload:"Upload", journal:"Journal", cash:"Cash Drop", reconcile:"Reconcile",
    reports:"Reports", history:"History", production:"Production KPI",
    staffPins:"Staff & PINs", activity:"Activity"
  },
  title:{
    upload:"Upload Opera Export", journal:"Audit Journal", cash:"Cash Drop",
    reconcile:"Reconciliation", reports:"Night Audit Report", history:"Audit History",
    production:"Production KPI", staffPins:"Staff & PINs", activity:"Activity"
  },
  app:{
    name:"Night Audit",
    expandMenu:"Expand menu", collapseMenu:"Collapse menu",
    identifiedAs:"Identified as", switchUser:"Switch", changePin:"Change PIN",
    connectFolder:"Connect folder", chromeEdgeOnly:"Chrome/Edge only",
    reconnectTo:"Reconnect to {0}", syncing:"Syncing…", syncFailed:"Sync failed",
    synced:"Synced {0}", folderConnected:"Folder connected",
    draftAutoSaved:"Draft auto-saved", noFileLoaded:"No file loaded",
    rowsPayroll:"{0} rows · {1} payroll",
    lightMode:"Switch to light mode", darkMode:"Switch to dark mode (easier on the eyes at night)",
    light:"Light", dark:"Dark",
    hideInstructions:"Hide instructions", showInstructions:"Show instructions", help:"Help",
    resumeTitle:"Resume unfinished audit?",
    resumeBody:"Found a draft for {0} with {1} transactions, last saved {2}.",
    recently:"recently", startFresh:"Start fresh", resumeAudit:"Resume audit",
    unresolvedFlagsTitle:"Unresolved flags",
    unresolvedFlagsBody:"{0} flagged item{1} have no linked correction. Approving now acknowledges these as open and carries them forward.",
    goBackResolve:"Go back — resolve first", ackAndSign:"Acknowledge & Sign",
    noComment:"no comment",
    homeBtn:"FO Portal", homeBtnTitle:"Back to the FO Portal Launcher (Alt+Home)"
  },
  toast:{
    loadedTx:"Loaded {0} transactions", fileEmpty:"File is empty",
    noRecognizableTx:"No recognizable Opera transactions found — check the column headers",
    readError:"Read error: {0}", resyncFileEmpty:"Re-sync file is empty",
    newRowsLinking:"{0} new rows · switch to Flagged to complete linking",
    resyncedNewRows:"Re-synced · {0} new row{1}",
    resyncedNoNew:"Re-synced · no new transactions",
    resyncError:"Re-sync error: {0}",
    identifyFirst:"Identify yourself first",
    submittedForReview:"Submitted for review ✓", auditApproved:"Audit approved ✓",
    useEdgeChrome:"Use Edge or Chrome for folder access",
    connected:"Connected: {0}",
    folderBlockedPolicy:"Folder access blocked — likely an IT policy. Use Save PDF / Save Excel to download files instead.",
    folderAccessFailedExport:"Folder access failed — use Save PDF / Save Excel to download files instead.",
    bgSyncFailed:"Background sync failed — your work is still safe in this tab, but reconnect the folder when you can",
    couldNotRestoreFolder:"Could not restore folder connection — reconnect in the sidebar",
    draftAutosaveFailed:"Draft autosave failed — storage may be full",
    generatingPdf:"Generating PDF…", pdfSavedTo:"PDF saved to {0} ✓", pdfDownloaded:"PDF downloaded ✓",
    openReportsFirst:"Open the Reports tab first",
    pdfLibFailed:"PDF library failed to load — check your connection",
    pdfExportFailed:"PDF export failed: {0}",
    excelLibUnavailable:"Excel library not available", noDataToExport:"No data to export",
    excelSavedTo:"Excel saved to {0} ✓", excelDownloaded:"Excel downloaded ✓",
    excelExportFailed:"Excel export failed: {0}",
    noDataToSave:"No data to save", auditSaved:"Audit saved ✓",
    savedLocallySyncFailed:"Saved locally — folder sync failed, reconnect and retry",
    auditResumed:"Audit resumed ✓",
    linkedSelfCorrected:"Linked as self-corrected ✓", correctionLinked:"Correction linked ✓",
    ploCardOnly:"PLO tagging only applies to card payments",
    nothingToLink:"Nothing to link here — link works on unflagged card/correction rows without an existing link",
    stepsIncomplete:"Complete these steps first: {0}",
    productionConfirmed:"Production KPI confirmed ✓",
    auditClosed:"Audit closed — business date rolled to {0} ✓",
    closedCannotOverwrite:"A closed audit already exists for {0} — it can't be overwritten",
    bizFeedWriteFailed:"Closed successfully, but couldn't publish the shared business-date feed — connect the shared PMS folder (Staff & PINs tab) so other apps see it",
    cashExceptionReasonRequired:"Enter a reason before marking the exception",
    cashExceptionSet:"Cash exception recorded ✓"
  },
  upload:{
    folderNeedsPermission:"Folder {0} needs permission. ",
    connectOneDrive:"Connect your OneDrive folder for auto-sync across sessions.",
    syncingTo:"Syncing to {0} · auto-saves every 5 min",
    auditDate:"Audit date",
    dropTitle:"Drop Opera cashier export here",
    dropSub:"or click to browse · .xlsx · .xls · .csv · .xml",
    resyncLabel:"Re-sync export",
    resyncDesc:" — drop an updated export to merge new postings while preserving your check/flag state.",
    dropUpdated:"Drop updated export",
    recentAudits:"Recent audits", transactions:"Transactions", corrections:"Corrections",
    cardTotal:"Card total"
  },
  cash:{
    empty:"Upload an Opera export first.",
    fxBanner:"Foreign currency in this drop — ",
    fxBannerEnd:". The physical count should include these banknotes, not SAR — don't expect SAR notes to cover this portion.",
    operaCashDrop:"Opera cash drop", fromSystem:"From system",
    physicalCounted:"Physical counted", enterBelow:"Enter below",
    variance:"Variance", zero:"Zero ✓", withinTolerance:"Within SAR {0} tolerance",
    cashCorrections:"Cash corrections",
    agent:"Agent", id:"ID", operaDebit:"Opera debit", operaCredit:"Opera credit",
    operaDrop:"Opera drop", physicalCountCol:"Physical count ↓", status:"Status",
    matchWord:"Match", shortWord:"Short", overWord:"Over",
    /* BRIEF-NIGHT-AUDIT-2-FIXES §2 — "no cash-drop slip recorded" exception */
    exceptionCol:"Exception", exceptionWord:"No slip (exception)",
    exceptionSetLabel:"No cash-drop slip recorded", exceptionClear:"Clear exception",
    exceptionReasonPh:"Reason (required) — e.g. \"agent forgot to fill the drop slip\"",
    exceptionMark:"Mark exception"
  },
  plo:{
    empty:"Upload an Opera export first.",
    howItWorksTitle:"How PLO works:",
    howItWorksBody:" In the Journal, find any card transaction processed outside the physical terminals and click ",
    howItWorksEnd:" on that row.",
    transactionsCount:"{0} transactions", ploTotal:"PLO total", tagged:"{0} tagged",
    noneTagged:"No PLO transactions tagged yet.",
    ploType:"PLO Type", card:"Card", receipt:"Receipt", amount:"Amount",
    remove:"Remove", subtotal:"{0} subtotal",
    typePaymentLink:"Payment Link", typeLaundry:"Laundry", typeOther:"Other"
  },
  machines:{
    desc:"Enter the Z-report amount and transaction count per card type from each terminal. Tab moves down through each card type for the current machine, then on to the next machine.",
    cardType:"Card type", machineTotal:"Machine total", operaTotal:"Opera total",
    amountPh:"amount", countPh:"# txns",
    amountMatch:"✓ Amount match", countMatch:"✓ Count match",
    delta:"Δ {0}", deltaTxn:"Δ {0}{1} txn{2}",
    grandTotal:"Grand total", txn:"txn", txns:"txns"
  },
  history:{
    empty:"No saved audits yet.",
    selfCorrected:"Self-corrected", flagResolved:"Flag-resolved", flagged:"Flagged",
    cash:"Cash", auditor:"Auditor",
    agentPerformance:"Agent performance — all nights",
    note:"Counts only corrections the auditor had to flag and chase down — self-corrected pairs aren't held against an agent.",
    nights:"Nights", auditorResolved:"Auditor-resolved corrections", avgPerNight:"Avg / night",
    totalCashDrop:"Total cash drop", trend:"Trend",
    lowErrors:"Low errors", review:"Review", monitor:"Monitor"
  },
  reconcile:{
    empty:"Upload an Opera export first.",
    /* No longer numbered "1 ·"/"2 ·"/"3 ·" (BRIEF-NIGHT-AUDIT-2 Phase N1) —
       these are now sub-sections nested under the guided flow's own
       "3 · Payments reconciled" step (reconcile.stepPaymentsReconciled),
       and the old numbering collided with the new outer 1-6 step numbers. */
    step1:"Machine Z-Reports", step2:"PLO Entries", step3:"Discrepancy Summary",
    balanceStatus:"Balance status", offBy:"SAR {0} off",
    operaCards:"Opera cards", machineZReports:"Machine Z-reports", plo:"PLO ({0})", ploCol:"PLO",
    cardType:"Card type", opera:"Opera", txns:"Txns", machineZ:"Machine Z",
    machineTxns:"Machine txns", ploTxns:"PLO txns", discrepancy:"Discrepancy",
    ok:"✓ OK", amountCountOff:"Amount + count off", amountOff:"Amount off", countOff:"Count off",
    balanced:"Balanced",
    summary:"Summary", transactions:"Transactions", corrections:"Corrections",
    checked:"Checked", flagged:"Flagged", totalCash:"Total cash",
    auditStatus:"Audit status",
    auditorSignOff:"Auditor sign-off", noteForNightMgr:"Note for Night Manager (optional):",
    auditorNotePh:"e.g. 'Visa machine 3 rolled over at midnight — Z-report split across 2 printouts'",
    auditorLabel:"Auditor:", submitForReview:"Submit for Review",
    submittedBy:"Submitted by ",
    auditorNoteLabel:"Auditor note:",
    nightMgrApproval:"Night Manager approval",
    unresolvedFlags:"{0} unresolved flag{1} — must acknowledge before approving",
    nightMgrNoteLabel:"Night Manager note (optional):",
    nightMgrNotePh:"e.g. 'Discrepancy on Amex noted — FDM to follow up with Amex in the morning'",
    nightMgrLabel:"Night Manager:",
    signaturePinNote:"Re-enters their PIN at the next step, like a signature.",
    approveAudit:"Approve Audit",
    approvedBy:"Approved by ",
    nightMgrNoteLabel2:"Night Manager note:",
    saveAudit:"Save audit · {0}",

    /* ── BRIEF-NIGHT-AUDIT-2 Phase N1 — guided "Submit the audit" steps ── */
    submitFlowTitle:"Submit the audit",
    stepJournalLoaded:"1 · Journal loaded",
    stepAccuracyReviewed:"2 · Accuracy reviewed",
    stepPaymentsReconciled:"3 · Payments reconciled",
    stepProduction:"4 · Production KPI confirmed",
    stepNightMgr:"5 · Night Manager sign-off",
    stepClose:"6 · Close — change business date",
    accuracyReviewedNote:"{0}/{1} transactions addressed (checked or flagged)",
    accuracyNotReviewed:"Check or flag every transaction in the Journal before continuing.",
    paymentsReconciledNote:"Card totals balance against Machine Z-Reports + PLO, and every cashier has been counted within tolerance.",
    paymentsNotReconciled:"Not balanced yet — resolve it in Machine Z-Reports/PLO above, count every cashier in Cash per Cashier below, or explain the variance in the note below so the audit can proceed.",
    varianceNoteLabel:"Variance explanation (required while unbalanced):",
    varianceNotePh:"e.g. \"Visa terminal 2 Z-report missing — chasing with FDM in the morning\"",
    productionIntro:"Review this week's Production KPI numbers before signing off — a specialist agent's low check-in/out count may be fully explained by courtesy/departure calls.",
    goToProduction:"Review Production KPI →",
    confirmProduction:"Confirm Production KPI reviewed",
    productionConfirmedBy:"Production KPI confirmed by ",
    stepsIncompleteToast:"Complete these steps first: {0}",
    closeIntro:"This is the commit point — mirrors the moment the real Opera night run completes and the auditor clicks to change the business date. Only close once that's actually happened; the audit stays open/amendable as \"Approved\" until then.",
    closingBusinessDate:"Closing business date:",
    newBusinessDateLabel:"New business date (after roll):",
    closeAndConfirm:"Close & Confirm",
    closedByLabel:"Closed by ",
    closedRolledTo:"This audit is closed and final — business date rolled to {0}.",
    closeSignatureNote:"Re-enters their PIN at the next step, like a signature — can be a different Night Manager than step 5's.",
    multiDateTitle:"Multiple business dates in this file",
    multiDateBody:"This file spans {0} different business dates — likely a catch-up run after a missed night. This audit will track and close as {1}; process the other date(s) in a separate upload once this one is closed.",
    gapsTitle:"Missing closed audit(s)",
    gapsBody:"No closed audit found for: {0} — investigate before treating this run as complete (BUSINESS-DATE.md: the business date may not have advanced, or a night run was missed).",

    /* ── BRIEF-NIGHT-AUDIT-2 Phase N2 — payment reconciliation ── */
    stepCashPerCashier:"Cash per Cashier",
    stepNonCardSettlements:"Non-Card Settlements",
    cashCountedOf:"{0}/{1} cashier{2} counted",
    cashReconciledNote:"Every cashier counted, within tolerance.",
    cashNotReconciledNote:"Not every cashier has been counted yet, or a variance exceeds tolerance.",
    goToCash:"Go to Cash tab →",
    nonCardIntro:"These settle directly — no terminal or PLO to check against. Listed here for a complete night total, not gated on a variance.",
    totalSettled:"Total settled (all payment types)",
    settledTxns:"{0} transaction{1}"
  },
  reports:{
    emptyUpload:"Upload an Opera export first.",
    draftStamp:"— DRAFT —", draftStampPlain:"DRAFT",
    title:"Night Audit Report",
    businessDate:"Business date: {0} · Generated: {1}",
    auditorLbl:"Auditor: ", nightMgrLbl:" · Night Manager: ",
    balanced:"✓ Balanced", discrepancy:"⚠ Discrepancy",
    cardRecon:"Card reconciliation",
    card:"Card", opera:"Opera", txns:"Txns", machines:"Machines", machTxns:"Mach. txns",
    plo:"PLO", ploTxns:"PLO txns", discCol:"Discrepancy", status:"Status",
    ok:"OK", amountCountOff:"Amount+count off", amountOff:"Amount off", countOff:"Count off",
    total:"Total", balancedBadge:"Balanced", discrepancyBadge:"Discrepancy",
    totalSettled:"Total settled (all payment types)",
    cashDrop:"Cash drop",
    toleranceNote:"Variances within SAR {0} are normal handling/rounding slack, shown as \"Within tolerance\" rather than a real discrepancy.",
    agent:"Agent", operaDrop:"Opera drop", physicalCount:"Physical count", variance:"Variance",
    nonCardSettlements:"Non-card settlements",
    nightAuditor:"Night Auditor", nightManager:"Night Manager", dateTime:"Date / Time",
    openFlagsAck:"Open flags acknowledged", none:"None", itemsCount:"{0} item(s)",
    journalTitle:"Night Audit — Final Journal",
    txCount:"{0} transactions",
    date:"Date", time:"Time", room:"Room", guest:"Guest", trx:"TRX",
    description:"Description", cardRef:"Card/Ref", debit:"Debit", credit:"Credit",
    receipt:"Receipt", st:"St", comment:"Comment",
    cashSubtotal:"Cash subtotal — {0}", netDrop:"Net drop: SAR {0}",
    correctionsSummary:"Corrections summary",
    roomGuest:"Room {0} · {1}",
    selfCorrectedByAgent:"Self-corrected by agent", flaggedThenCorrected:"Flagged by auditor, then corrected",
    original:"⚑ Original: ", reversal:"↩ Reversal: ",
    openFlagsUnresolved:"Open flags (unresolved at time of report)",
    tabSummary:"Reconciliation Summary", tabJournal:"Final Journal Report",
    savePdf:"Save PDF", saveExcel:"Save Excel", print:"Print", exportJson:"Export JSON",
    footnote:"PDF/Print bundle both reports; Excel is typed data across tabs (Summary, Journal, Cash, PLO)",
    writtenToFolder:" · written to your connected folder.", downloaded:" · downloaded."
  },
  journal:{
    empty:"Upload an Opera export first.",
    filterAll:"All ({0})", filterUnchecked:"Unchecked ({0})", filterPayments:"Payments ({0})",
    filterCharges:"Charges ({0})", filterCards:"Cards ({0})", filterCash:"Cash ({0})",
    filterCorrections:"Corrections ({0})", filterPlo:"PLO ({0})",
    filterFlagged:"Flagged ({0})", filterNew:"New ({0})",
    progress:"Journal progress", checkedOf:"{0}/{1} checked", nFlagged:"{0} flagged",
    checkAll:"Check all", resync:"Re-sync",
    keysLegend:"Keys: ",
    keyCheck:" check  ", keyFlag:" flag  ", keyNote:" note  ", keyPlo:" PLO  ",
    keyLink:" link  ", keyPick:" pick from an open PLO/link list  ",
    keyTab:" next unchecked  ", keyArrows:" navigate  ", keyEsc:" close  1–8 filter",
    date:"Date", time:"Time", room:"Room", guest:"Guest", trx:"TRX",
    description:"Description", cardRef:"Card/Ref", debit:"Debit", credit:"Credit",
    cashier:"Cashier", user:"User", receipt:"Receipt", plo:"PLO", flag:"Flag",
    cash:"Cash", cityLedger:"City Ledger",
    corrTitle:"Negative amount or a 'correct' reference — verify against the original posting",
    corrBadge:"Corr",
    taxIncludes:"Includes {0} tax/fee line{1}: ",
    taxTotalIncl:" — total incl. tax: SAR {0}. Checking this row checks them all.",
    taxBadge:"+Tax", taxBadgeN:"+Tax ({0})",
    fxTitle:"Tendered in {0} {1} at rate {2} → converted to SAR {3} for reconciliation. Physical count should expect {0} cash here, not SAR.",
    checkedTip:"Checked — click to uncheck", flaggedTip:"Flagged — click to expand",
    verifyTip:"Verify: type & transaction match the slip · amount matches · approved, not declined — then click to check",
    ploKeyTip:"Key: P (focus this row, then P)", ploLabel:"PLO",
    removePloTag:"Remove PLO tag",
    selfCorrected:"Self-corrected", corrected:"Corrected", unlink:"Unlink",
    linkedFrom:"Linked from ", addComment:"Add comment…",
    flagBtn:"Flag",
    linkKeyTip:"Link this to its matching transaction — for routine self-corrections that don't need a flag. Key: L (focus this row, then L)",
    linkBtn:"Link",
    describeWrong:"Describe what's wrong:",
    flagPh:"e.g. \"posted as Visa, voucher shows Mastercard\" or \"amount should be 1501.21\"",
    correctionLinked:"Correction linked",
    suggestedMatches:"Suggested matches — click to link:",
    score:"Score {0}", confirmArrow:"Confirm →",
    enterReversalPrompt:"Enter Reversal TRX_NO:", enterManually:"Enter manually",
    clearFlag:"Clear flag", collapse:"Collapse",
    linkToMatch:"Link to its matching transaction — for a routine self-correction, no flag or comment needed:",
    noObviousMatch:"No obvious match found in this export.",
    enterMatchingPrompt:"Enter the matching TRX_NO:", cancel:"Cancel", linkArrow:"Link →",
    noMatchFilter:"No transactions match this filter.",
    onChargeAbove:"On the charge above"
  },
  production:{
    noShiftFeedFolder:"No shift-feed folder found in there — pick the Attendance Records folder (Records/Attendance/), and make sure Attendance has synced at least one roster week",
    loadedShiftHours:"Loaded shift-hours for {0} employee-day{1} ✓",
    failedShiftFeed:"Failed to read shift-feed: {0}",
    useEdgeChrome:"Use Edge or Chrome for folder access",
    folderAccessFailed:"Folder access failed: {0}",
    expectedXml:"{0}: expected a .xml activity-log export",
    noActivityRecords:"{0}: no activity records found",
    newEventsLoaded:"{0}: {1} new event{2} loaded ({3} in file)",
    fileError:"{0}: {1}",
    pickWeekFirst:"Pick a week first",
    savedFile:"Saved {0} ✓", downloadedFile:"Downloaded {0} ✓",
    saveFailed:"Save failed: {0}",
    excelLibUnavailable:"Excel library not available", excelExportFailed:"Excel export failed: {0}",
    week:"Week", noHistoryYet:"No journal history or activity log loaded yet",
    exportExcel:"Export Excel", saveWeeklyRecord:"Save weekly record", saving:"Saving…",
    noFolderConnected:"No folder connected — both buttons above will download to your browser instead. ",
    connectFromUpload:"Connect a folder from the Upload tab to save straight to your records folder.",
    checkInOutLog:"Check-in / check-out log",
    eventsLoaded:"{0} event{1} loaded across all weeks. ",
    exportsFiltered:"Opera exports are often filtered to one action type — upload check-in and check-out files separately, they merge automatically.",
    uploadActivityXml:"Upload activity-log XML",
    rosterLink:"Roster link (Attendance)",
    connectedShiftHours:"Connected: {0}. ",
    shiftHoursLoaded:"Shift-hours loaded for {0} week{1}.",
    noShiftHoursYet:"No shift-hours loaded yet — click Refresh.",
    connectAttendanceDesc:"Connect Attendance's Records folder to normalize Volume by hours actually worked, instead of a raw weekly count. Optional — everything above already works without it.",
    refresh:"Refresh", loadingEllipsis:"Loading…",
    connectAttendanceFolder:"Connect Attendance folder", reconnect:"Reconnect",
    guestCareLink:"Guest Care link (call-events)",
    connectedCallEvents:"Connected via the shared PMS folder. ",
    callEventsLoaded:"Call-events loaded for {0} day{1}.",
    noCallEventsYet:"No call-events loaded yet — click Refresh.",
    connectGuestCareDesc:"Connect the shared PMS folder (Staff & PINs tab) to credit Guest Care's courtesy/departure calls as Production volume units — a call-duty agent's output stays fair even with fewer check-ins/outs. Optional — everything above already works without it.",
    failedCallEvents:"Failed to read call-events: {0}",
    courtesyCalls:"Courtesy calls", departureCalls:"Departure calls",
    ptsPerCourtesyCall:"Pts / courtesy call", ptsPerDepartureCall:"Pts / departure call",
    dashboard:"Dashboard",
    mapStaffFirst:"Map at least one staff member below to see the dashboard.",
    leaderboard1:"Leaderboard #1 (display only)", scorePct:"{0}% score",
    teamAccuracy:"Team accuracy (avg)", totalUnits:"Total units",
    fairShare:"Fair share (100% ÷ staff)", mappedStaff:"Mapped staff",
    scoreByStaff:"Score by staff", volumeBreakdown:"Volume breakdown",
    scoreTrend:"Score trend — last {0} week{1}",
    detail:"Detail",
    rankTip:"Leaderboard position — display only, not part of the score", rank:"Rank",
    staff:"Staff", id:"ID", staffIdCol:"Staff ID", journalTx:"Journal tx", checkIns:"Check-ins", checkOuts:"Check-outs",
    units:"Units", volumeModel:"Volume model", hrsMetOnDuty:"Hrs met/on-duty",
    dutyHrsTip:"From the Attendance shift-feed link, if connected", dutyHrs:"Duty hrs",
    coverageTip:"Hours on duty where this person's share of that hour's activity met or exceeded their expected share, given how many colleagues were on duty the same hour",
    coverage:"Coverage",
    flaggedHrsTip:"On-duty hours where this person's share cleared the flag margin — see Scoring settings",
    flaggedHrs:"Flagged hrs", corrections:"Corrections", accuracy:"Accuracy", score:"Score",
    noMappedStaff:"No mapped staff yet — add entries in Staff mapping below.",
    noEmployeeIdTip:"No Employee ID — won't join with other KPIs", missing:"missing",
    noAttendanceFallback:"No Attendance shift-feed hours this week — falling back to share of team total units",
    fallbackPct:"fallback {0}%",
    hrsMet:"{0}/{1} hrs",
    flaggedHoursTip:"Over-performed the flag margin this many on-duty hours",
    coverageFootnote:"Coverage = on-duty hours where this person met or beat their expected share (100% ÷ colleagues on duty that hour), from the Attendance link. ",
    scoreFootnote:"Score = {0}% × volume score + {1}% × accuracy score (each scored threshold→target→stretch, rank shown for reference only). ",
    fallbackNote:"Rows marked \"fallback\" have no Attendance hours this week and use the team-fair-share model instead (fair share this week: {0}%, team total units: {1}).",
    connectForHourly:"Connect the Attendance folder above for the hourly coverage model — everyone here is on the fallback team-fair-share model (fair share: {0}%, team total units: {1}).",
    unmappedTitle:"Unmapped identities this week — excluded from scoring until mapped",
    unmappedAgents:"Cashier IDs (journal)", unmappedUsers:"Opera usernames (activity log)",
    assignTo:"Assign {0} to:", chooseStaff:"Choose staff…", assign:"Assign", cancel:"Cancel",
    staffMapping:"Staff mapping",
    staffId:"Staff ID", name:"Name", cashierId:"Cashier ID", operaUsernames:"Opera username(s)",
    cashierIdPh:"e.g. 101", usernamePh:"HB4X1-AALDOSSARI@ACCOREN", clear:"Clear",
    noRegistryStaff:"No staff in the shared registry yet — connect the PMS folder from Staff & PINs.",
    scoringSettings:"Scoring settings",
    weights:"Weights", volumeWeight:"Volume weight %", accuracyWeight:"Accuracy weight %",
    ptsPerTx:"Pts / journal tx", ptsPerCheckIn:"Pts / check-in", ptsPerCheckOut:"Pts / check-out",
    hourlyModelTitle:"Hourly coverage model (primary — requires the Attendance link above)",
    flagMargin:"Flag margin ×", bonusPerFlag:"Bonus pts / flagged hr",
    thresholdPct:"Threshold %", targetPct:"Target %", stretchPct:"Stretch %",
    hourlyExplain:"For every hour a mapped staff member was on duty (per the Attendance shift-feed), their share of that hour's activity is compared to their expected share (100% ÷ colleagues on duty that hour). \"Coverage\" = % of on-duty hours they met or beat their expected share. An hour where their share clears {0}× their expected share is FLAGGED and adds {1} bonus points. Volume metric = Coverage % + (flagged hours × bonus), scored against Threshold/Target/Stretch above. Anyone with zero on-duty hours this week (Attendance link not connected, or not yet mapped there) falls back to the team-fair-share model below.",
    fallbackTitle:"Fallback: team-fair-share threshold / target / stretch (× team fair share — auto-adjusts to team size)",
    thresholdX:"Threshold ×", targetX:"Target ×", stretchX:"Stretch ×",
    thisWeeksTts:"= this week's threshold/target/stretch",
    accuracyTitle:"Accuracy threshold / target / stretch (%)",
    finalExplain:"Fallback Volume % (only used without an Attendance link) = agent's units ÷ team's total units this week, scored Threshold (0%) → Target (100%) → capped bonus to 110% at Stretch — never step tiers. Its Threshold/Target/Stretch are multiples of the team's fair share (100% ÷ mapped staff), auto-scaling as staff join or leave. Accuracy = 1 − corrections ÷ own journal transactions, scored the same way against its own Threshold/Target/Stretch. Final score = weighted combination of the (fallback or hourly) volume score and the accuracy score (not the raw ratios)",
    finalExplainWeighted:" (currently equivalent to {0}% volume / {1}% accuracy)",
    finalExplainEnd:". Rank (leaderboard position) is DISPLAY ONLY — it is never part of the score. Changes apply immediately and persist."
  },
  status:{draft:"Draft",submitted:"Submitted for Review",approved:"Approved",closed:"Closed"},
  xlsx:{
    businessDateLabel:"Business date", cardBalance:"Card balance", offBySar:"Off by SAR {0}",
    countBalance:"Count balance", offByTxn:"Off by {0} txn", submittedLabel:"Submitted",
    approvedLabel:"Approved", ok:"OK",
    hdrCard:"Card", hdrOperaSar:"Opera (SAR)", hdrOperaTxns:"Opera txns",
    hdrMachSar:"Machine Z (SAR)", hdrMachTxns:"Machine txns", hdrPloSar:"PLO (SAR)", hdrPloTxns:"PLO txns",
    hdrAmtDiscSar:"Amount disc (SAR)", hdrCountDisc:"Count disc",
    nonCardSettlements:"Non-Card Settlements",
    totalSettledSar:"Total Settled (SAR)", totalSettledTxns:"Total Settled Txns",
    totalsSection:"Totals", totalCashSar:"Total cash (SAR)",
    trxNo:"TRX No", code:"Code", cashierId:"Cashier ID", cashier:"Cashier", user:"User",
    operaRef:"Opera Ref", trxType:"Transaction Type",
    fxCurrency:"FX Currency", fxFaceAmt:"FX Face Amt", fxRate:"FX Rate",
    ploType:"PLO Type", comment:"Comment", correctionLink:"Correction Link", linkedAt:"Linked At",
    txTypeTax:"Tax", txTypeCorrection:"Correction", txTypeCard:"Card Payment", txTypeCash:"Cash",
    txTypeCL:"City Ledger", txTypeReward:"Reward Points", txTypeCharge:"Charge", txTypeOTA:"OTA Settlement",
    correctedBy:"Corrected by {0}", reversalOf:"Reversal of {0}",
    cashTxns:"Cash Txns", operaDebitSar:"Opera Debit (SAR)", operaCreditSar:"Opera Credit (SAR)",
    operaDropSar:"Opera Drop (SAR)", physicalCountSar:"Physical Count (SAR)", varianceSar:"Variance (SAR)",
    pctOfNightDrop:"% of Night Drop",
    machine:"Machine", sarSuffix:" (SAR)", txnsSuffix:" (Txns)",
    machineTotalSar:"Machine Total (SAR)", machineTotalTxns:"Machine Total (Txns)",
    grandTotal:"Grand Total", txnCountsHeader:"── Transaction counts ──",
    cardRefMasked:"Card/Ref (masked)", amountSar:"Amount (SAR)",
    resolvedCorrections:"Resolved corrections", origTrx:"Orig TRX",
    originalDescription:"Original Description", origAmtSar:"Orig Amt (SAR)",
    revTrx:"Rev TRX", revDate:"Rev Date", revCashier:"Rev Cashier",
    reversalDescription:"Reversal Description", revAmtSar:"Rev Amt (SAR)", source:"Source",
    selfCorrectedLabel:"Self-corrected", flaggedThenCorrectedLabel:"Flagged then corrected",
    openFlagsUnresolvedLabel:"Open flags (unresolved)", creditSar:"Credit (SAR)", debitSar:"Debit (SAR)",
    noCommentLower:"no comment"
  },
  identity:{
    loadingStaff:"Loading…",
    whoIsUsing:"Who's using {0}?",
    enterIdThenPin:"Enter your Employee ID, then your 4-digit PIN.",
    resumeFolderAccess:"Resume folder access",
    idFieldLabel:"Employee ID", continueBtn:"Continue", continueUnattributed:"Continue without signing in (shared use)",
    locked:"Locked",
    unattributedName:"Front Desk (unattributed)",
    firstTimeConfirm:"Type it again to confirm", firstTimeChoose:"First time — choose a 4-digit PIN",
    enterYourPin:"Enter your 4-digit PIN",
    lockedHelp:"Locked after 5 wrong PINs — ask a night manager to reset it.",
    notYouBack:"Not you? Back",
    didntMatch:"Didn't match — try again from the start.",
    pinTooEasy:"That PIN is too easy to guess — pick another.",
    couldntSetPin:"Couldn't set PIN — try again.",
    unknownId:"We don't recognize this Employee ID.",
    notSynced:"This app hasn't synced the staff list yet — connect the PMS folder, or ask a night manager.",
    inactive:"This Employee ID is no longer active.",
    noPinYet:"No PIN set for this ID yet — ask a night manager to set one.",
    lockedTryReset:"Locked after 5 wrong PINs — ask a night manager to reset it.",
    wrongPin:"Wrong PIN — try again.",
    cantIdentify:"Can't identify — ask a night manager for help.",
    signOffTitle:"Night Manager sign-off",
    noNightManager:"No Night Manager or top admin is set up yet — ask a top admin to grant the Night Manager role in Staff & PINs.",
    whoIsApproving:"Who is approving this audit?",
    signAs:"Sign as {0}",
    lockedFivePins:"Locked after 5 wrong PINs.",
    cantSignOff:"Can't sign off here.",
    resetPinTitle:"Reset PIN — {0}", setPinTitle:"Set PIN — {0}",
    handKeyboard:"Hand the keyboard to {0} — {1}",
    confirmOnceMore:"confirm it once more.", chooseFourDigit:"choose a 4-digit PIN.",
    didntMatchStart:"Didn't match — start again.",
    tooEasyPick:"Too easy to guess — pick another.", couldntSetPin2:"Couldn't set PIN.",
    folderAccessFailedChrome:"Folder access failed — use Chrome or Edge",
    sharedRegistry:"Shared staff registry",
    connectedSync:"Connected: {0} — PINs and roles sync with every other PMS app.",
    notConnected:"Not connected — PINs work on this device only until you connect the shared PMS folder (the same top-level folder Guest Care connects to).",
    filesProtocolMsg:"Folder connection needs the local server — open via \"Open PMS Apps.bat\", not by double-clicking this file.",
    connectPmsFolder:"Connect PMS folder", reconnectPmsFolder:"Reconnect PMS folder",
    settings:"Settings", idleTimeout:"Idle timeout (minutes)",
    allowUnattributed:"Allow \"Front Desk (unattributed)\" tile",
    staffCount:"Staff ({0})",
    name:"Name", position:"Position", status:"Status", pin:"PIN", roleCol:"Night Audit role",
    active:"Active", inactive:"Inactive",
    resetPinBtn:"Reset PIN", setPinBtn:"Set PIN",
    viewer:"viewer", topAdminBadge:"top admin",
    roleAuditor:"Auditor", roleNightManager:"Night Manager",
    permissionsMatrix:"Permissions matrix — which tabs each role sees",
    externalCount:"External ({0})", addExternalMember:"+ Add external member",
    externalDesc:"Non-FO people (e.g. an assessor) — excluded from production scores and every export; visible on this app's identify grid only once granted a role here.",
    noExternalYet:"No external members yet.",
    positionDept:"Position / dept.",
    addExternalTitle:"Add external member",
    nameLabel:"Name", idLabel:"ID",
    displayNameOptional:"Display name (optional — defaults to name)",
    positionLabel:"Position", departmentOptional:"Department (optional)",
    add:"Add",
    editTitle:"Edit — {0}", displayNameLabel:"Display name", departmentLabel:"Department",
    requiredNameIdPos:"Name, ID, and position are required.",
    idInUse:"That ID is already in use — edit it.",
    idMustStartExt:"ID must start with \"ext-\".", couldntAddPerson:"Couldn't add this person.",
    requiredNameDisplayPos:"Name, display name, and position are required.",
    couldntSaveChanges:"Couldn't save changes.",
    activityTitle:"Activity — {0} of {1} (this device)",
    everyone:"Everyone", allActions:"All actions", to:"to",
    nothingLogged:"Nothing logged yet.",
    when:"When", who:"Who", action:"Action", target:"Target", detail:"Detail"
  }
},
ar:{
  common:{
    sar:"ر.س", cancel:"إلغاء", save:"حفظ", close:"إغلاق", loading:"جاري التحميل…",
    yes:"نعم", no:"لا", edit:"تعديل", clear:"مسح", assign:"إسناد", refresh:"تحديث",
    connect:"ربط", reconnect:"إعادة الربط", back:"رجوع", collapse:"طي",
    balanced:"✓ متطابق", discrepancy:"فارق", pending:"معلّق", status:"الحالة",
    total:"الإجمالي", date:"التاريخ", time:"الوقت", room:"الغرفة", guest:"النزيل", agent:"الموظف",
    dash:"–", none:"لا يوجد", delayed:"متأخر", delayedDays:"متأخر · {0} يوم{1}"
  },
  nav:{
    upload:"الرفع", journal:"اليومية", cash:"التحصيل النقدي", reconcile:"المطابقة",
    reports:"التقارير", history:"الأرشيف", production:"الإنتاجية",
    staffPins:"الموظفون والرموز", activity:"العمليات"
  },
  title:{
    upload:"رفع ملف أوبرا", journal:"يومية التدقيق", cash:"التحصيل النقدي",
    reconcile:"المطابقة", reports:"تقرير التدقيق الليلي", history:"أرشيف التدقيق",
    production:"مؤشر الإنتاجية", staffPins:"الموظفون والرموز", activity:"سجل العمليات"
  },
  app:{
    name:"التدقيق الليلي",
    expandMenu:"توسيع القائمة", collapseMenu:"طي القائمة",
    identifiedAs:"مسجَّل الدخول باسم", switchUser:"تبديل", changePin:"تغيير الرمز",
    connectFolder:"ربط مجلد", chromeEdgeOnly:"متصفح كروم أو إيدج فقط",
    reconnectTo:"إعادة الاتصال بـ {0}", syncing:"جارٍ المزامنة…", syncFailed:"فشلت المزامنة",
    synced:"آخر مزامنة {0}", folderConnected:"المجلد متصل",
    draftAutoSaved:"تم حفظ المسودة تلقائياً", noFileLoaded:"لا يوجد ملف محمَّل",
    rowsPayroll:"{0} صف · {1} في كشف الرواتب",
    lightMode:"التحويل للوضع الفاتح", darkMode:"التحويل للوضع الداكن (أريح للعين ليلاً)",
    light:"فاتح", dark:"داكن",
    hideInstructions:"إخفاء التعليمات", showInstructions:"عرض التعليمات", help:"مساعدة",
    resumeTitle:"استئناف تدقيق غير مكتمل؟",
    resumeBody:"تم العثور على مسودة لتاريخ {0} تحتوي على {1} معاملة، آخر حفظ {2}.",
    recently:"قبل قليل", startFresh:"البدء من جديد", resumeAudit:"استئناف التدقيق",
    unresolvedFlagsTitle:"إشارات غير محلولة",
    unresolvedFlagsBody:"{0} عنصر عليه إشارة{1} دون تصحيح مرتبط به. الاعتماد الآن يُقرّ بهذه العناصر كمفتوحة ويرحّلها للمتابعة.",
    goBackResolve:"الرجوع — الحل أولاً", ackAndSign:"إقرار واعتماد",
    noComment:"لا توجد ملاحظة",
    homeBtn:"FO Portal", homeBtnTitle:"العودة إلى منصّة FO Portal الرئيسية (Alt+Home)"
  },
  toast:{
    loadedTx:"تم تحميل {0} معاملة", fileEmpty:"الملف فارغ",
    noRecognizableTx:"لم يتم التعرف على أي معاملات أوبرا — تحقق من عناوين الأعمدة",
    readError:"خطأ في القراءة: {0}", resyncFileEmpty:"ملف إعادة المزامنة فارغ",
    newRowsLinking:"{0} صف جديد · انتقل إلى المُشار عليها لإتمام الربط",
    resyncedNewRows:"تمت إعادة المزامنة · {0} صف جديد{1}",
    resyncedNoNew:"تمت إعادة المزامنة · لا توجد معاملات جديدة",
    resyncError:"خطأ في إعادة المزامنة: {0}",
    identifyFirst:"سجّل دخولك أولاً",
    submittedForReview:"تم الإرسال للمراجعة ✓", auditApproved:"تم اعتماد التدقيق ✓",
    useEdgeChrome:"استخدم متصفح إيدج أو كروم للوصول إلى المجلد",
    connected:"تم الاتصال: {0}",
    folderBlockedPolicy:"تم حظر الوصول إلى المجلد — غالباً بسبب سياسة تقنية المعلومات. استخدم حفظ PDF / حفظ Excel لتنزيل الملفات بدلاً من ذلك.",
    folderAccessFailedExport:"فشل الوصول إلى المجلد — استخدم حفظ PDF / حفظ Excel لتنزيل الملفات بدلاً من ذلك.",
    bgSyncFailed:"فشلت المزامنة في الخلفية — عملك ما زال محفوظاً في هذه النافذة، لكن أعد ربط المجلد عندما تستطيع",
    couldNotRestoreFolder:"تعذّرت استعادة اتصال المجلد — أعد الربط من الشريط الجانبي",
    draftAutosaveFailed:"فشل الحفظ التلقائي للمسودة — قد تكون مساحة التخزين ممتلئة",
    generatingPdf:"جارٍ إنشاء PDF…", pdfSavedTo:"تم حفظ PDF في {0} ✓", pdfDownloaded:"تم تنزيل PDF ✓",
    openReportsFirst:"افتح شاشة التقارير أولاً",
    pdfLibFailed:"فشل تحميل مكتبة PDF — تحقق من اتصالك بالإنترنت",
    pdfExportFailed:"فشل تصدير PDF: {0}",
    excelLibUnavailable:"مكتبة Excel غير متاحة", noDataToExport:"لا توجد بيانات للتصدير",
    excelSavedTo:"تم حفظ Excel في {0} ✓", excelDownloaded:"تم تنزيل Excel ✓",
    excelExportFailed:"فشل تصدير Excel: {0}",
    noDataToSave:"لا توجد بيانات للحفظ", auditSaved:"تم حفظ التدقيق ✓",
    savedLocallySyncFailed:"تم الحفظ محلياً — فشلت مزامنة المجلد، أعد الربط وحاول مجدداً",
    auditResumed:"تم استئناف التدقيق ✓",
    linkedSelfCorrected:"تم الربط كتصحيح ذاتي ✓", correctionLinked:"تم ربط التصحيح ✓",
    ploCardOnly:"وضع إشارة PLO يُطبَّق فقط على دفعات البطاقات",
    nothingToLink:"لا يوجد ما يُربط هنا — الربط يعمل فقط على صفوف بطاقة/تصحيح غير مُشار عليها وبلا ربط سابق",
    stepsIncomplete:"أكمل هذه الخطوات أولاً: {0}",
    productionConfirmed:"تم تأكيد مؤشر الإنتاجية ✓",
    auditClosed:"تم إغلاق التدقيق — تم ترحيل تاريخ العمل إلى {0} ✓",
    closedCannotOverwrite:"يوجد بالفعل تدقيق مُغلق لـ {0} — لا يمكن الكتابة فوقه",
    bizFeedWriteFailed:"تم الإغلاق بنجاح، لكن تعذّر نشر ملف تاريخ العمل المشترك — اربط مجلد النظام المشترك (تبويب الموظفون والرموز) ليظهر لبقية التطبيقات",
    cashExceptionReasonRequired:"أدخل السبب قبل تسجيل الاستثناء",
    cashExceptionSet:"تم تسجيل استثناء النقدية ✓"
  },
  upload:{
    folderNeedsPermission:"المجلد {0} يحتاج إذن وصول. ",
    connectOneDrive:"اربط مجلد OneDrive الخاص بك للمزامنة التلقائية بين الجلسات.",
    syncingTo:"جارٍ المزامنة مع {0} · حفظ تلقائي كل 5 دقائق",
    auditDate:"تاريخ التدقيق",
    dropTitle:"أسقط ملف أوبرا للكاشير هنا",
    dropSub:"أو انقر للاستعراض · .xlsx · .xls · .csv · .xml",
    resyncLabel:"إعادة مزامنة الملف",
    resyncDesc:" — أسقط ملفاً محدَّثاً لدمج القيود الجديدة مع الإبقاء على حالة التحقق/الإشارات.",
    dropUpdated:"أسقط الملف المحدَّث",
    recentAudits:"عمليات التدقيق الأخيرة", transactions:"المعاملات", corrections:"التصحيحات",
    cardTotal:"إجمالي البطاقات"
  },
  cash:{
    empty:"ارفع ملف أوبرا أولاً.",
    fxBanner:"عملة أجنبية في هذا التحصيل — ",
    fxBannerEnd:". يجب أن يشمل العدّ الفعلي هذه الأوراق النقدية، وليس الريال — لا تتوقع أن تغطي أوراق الريال هذا الجزء.",
    operaCashDrop:"التحصيل النقدي في أوبرا", fromSystem:"من النظام",
    physicalCounted:"العدّ الفعلي", enterBelow:"أدخل أدناه",
    variance:"الفارق", zero:"صفر ✓", withinTolerance:"ضمن هامش {0} ريال",
    cashCorrections:"تصحيحات نقدية",
    agent:"الموظف", id:"الرقم", operaDebit:"مدين أوبرا", operaCredit:"دائن أوبرا",
    operaDrop:"تحصيل أوبرا", physicalCountCol:"العدّ الفعلي ↓", status:"الحالة",
    matchWord:"مطابق", shortWord:"عجز", overWord:"زيادة",
    exceptionCol:"استثناء", exceptionWord:"لا يوجد إيصال (استثناء)",
    exceptionSetLabel:"لم يُسجَّل إيصال تسليم النقدية", exceptionClear:"إلغاء الاستثناء",
    exceptionReasonPh:"السبب (مطلوب) — مثال: \"نسي الموظف تعبئة إيصال التسليم\"",
    exceptionMark:"تسجيل استثناء"
  },
  plo:{
    empty:"ارفع ملف أوبرا أولاً.",
    howItWorksTitle:"كيف تعمل PLO:",
    howItWorksBody:" في اليومية، ابحث عن أي دفعة بطاقة تمت خارج الأجهزة الفعلية وانقر على ",
    howItWorksEnd:" في ذلك الصف.",
    transactionsCount:"{0} معاملة", ploTotal:"إجمالي PLO", tagged:"{0} موسومة",
    noneTagged:"لا توجد معاملات PLO موسومة بعد.",
    ploType:"نوع PLO", card:"البطاقة", receipt:"الإيصال", amount:"المبلغ",
    remove:"إزالة", subtotal:"مجموع {0}",
    typePaymentLink:"رابط دفع", typeLaundry:"مغسلة", typeOther:"أخرى"
  },
  machines:{
    desc:"أدخل مبلغ تقرير الإغلاق (Z-Report) وعدد المعاملات لكل نوع بطاقة من كل جهاز. مفتاح Tab ينتقل عبر أنواع البطاقات للجهاز الحالي، ثم إلى الجهاز التالي.",
    cardType:"نوع البطاقة", machineTotal:"إجمالي الجهاز", operaTotal:"إجمالي أوبرا",
    amountPh:"المبلغ", countPh:"عدد المعاملات",
    amountMatch:"✓ تطابق المبلغ", countMatch:"✓ تطابق العدد",
    delta:"فرق {0}", deltaTxn:"فرق {0}{1} معاملة{2}",
    grandTotal:"الإجمالي الكلي", txn:"معاملة", txns:"معاملات"
  },
  history:{
    empty:"لا توجد عمليات تدقيق محفوظة بعد.",
    selfCorrected:"تصحيح ذاتي", flagResolved:"محلول بإشارة", flagged:"عليه إشارة",
    cash:"نقدي", auditor:"المدقق",
    agentPerformance:"أداء الموظفين — كل الليالي",
    note:"يُحتسب فقط التصحيحات التي اضطر المدقق لوضع إشارة عليها ومتابعتها — التصحيحات الذاتية لا تُحسب على الموظف.",
    nights:"عدد الليالي", auditorResolved:"تصحيحات حلّها المدقق", avgPerNight:"المعدل / الليلة",
    totalCashDrop:"إجمالي التحصيل النقدي", trend:"الاتجاه",
    lowErrors:"أخطاء قليلة", review:"يحتاج مراجعة", monitor:"يحتاج متابعة"
  },
  reconcile:{
    empty:"ارفع ملف أوبرا أولاً.",
    step1:"تقارير إغلاق الأجهزة", step2:"إدخالات PLO", step3:"ملخص الفارق",
    balanceStatus:"حالة التطابق", offBy:"فارق {0} ريال",
    operaCards:"بطاقات أوبرا", machineZReports:"تقارير إغلاق الأجهزة", plo:"PLO ({0})", ploCol:"PLO",
    cardType:"نوع البطاقة", opera:"أوبرا", txns:"المعاملات", machineZ:"إغلاق الجهاز",
    machineTxns:"معاملات الجهاز", ploTxns:"معاملات PLO", discrepancy:"الفارق",
    ok:"✓ متطابق", amountCountOff:"فارق مبلغ وعدد", amountOff:"فارق مبلغ", countOff:"فارق عدد",
    balanced:"متطابق",
    summary:"الملخص", transactions:"المعاملات", corrections:"التصحيحات",
    checked:"محقَّق", flagged:"عليه إشارة", totalCash:"إجمالي النقدي",
    auditStatus:"حالة التدقيق",
    auditorSignOff:"اعتماد المدقق", noteForNightMgr:"ملاحظة لمدير المناوبة الليلية (اختياري):",
    auditorNotePh:"مثال: «جهاز فيزا 3 تجاوز منتصف الليل — تقرير الإغلاق مقسّم على إيصالين»",
    auditorLabel:"المدقق:", submitForReview:"إرسال للمراجعة",
    submittedBy:"تم الإرسال بواسطة ",
    auditorNoteLabel:"ملاحظة المدقق:",
    nightMgrApproval:"اعتماد مدير المناوبة الليلية",
    unresolvedFlags:"{0} إشارة غير محلولة{1} — يجب الإقرار بها قبل الاعتماد",
    nightMgrNoteLabel:"ملاحظة مدير المناوبة الليلية (اختياري):",
    nightMgrNotePh:"مثال: «فارق في أمكس مُلاحظ — سيتابعه FDM مع أمكس صباحاً»",
    nightMgrLabel:"مدير المناوبة الليلية:",
    signaturePinNote:"سيُدخل رمزه في الخطوة التالية، كتوقيع.",
    approveAudit:"اعتماد التدقيق",
    approvedBy:"تم الاعتماد بواسطة ",
    nightMgrNoteLabel2:"ملاحظة مدير المناوبة الليلية:",
    saveAudit:"حفظ التدقيق · {0}",

    /* ── BRIEF-NIGHT-AUDIT-2 المرحلة N1 — خطوات "إنهاء التدقيق" الموجَّهة.
       مصطلحات مقترحة، بحاجة لمراجعة خالد (LANGUAGE.md). ── */
    submitFlowTitle:"خطوات إنهاء التدقيق",
    stepJournalLoaded:"1 · تحميل اليومية",
    stepAccuracyReviewed:"2 · مراجعة الدقة",
    stepPaymentsReconciled:"3 · مطابقة المدفوعات",
    stepProduction:"4 · تأكيد مؤشر الإنتاجية",
    stepNightMgr:"5 · اعتماد مدير المناوبة الليلية",
    stepClose:"6 · الإغلاق — تغيير تاريخ العمل",
    accuracyReviewedNote:"{0}/{1} معاملة تمت مراجعتها (محقَّقة أو عليها إشارة)",
    accuracyNotReviewed:"حقِّق أو ضع إشارة على كل معاملة في اليومية قبل المتابعة.",
    paymentsReconciledNote:"إجماليات البطاقات متطابقة مع تقارير إغلاق الأجهزة و PLO، وتم عدّ جميع الكاشيرين ضمن الحد المسموح.",
    paymentsNotReconciled:"لم تتطابق بعد — عالِج الفارق في تقارير إغلاق الأجهزة/PLO أعلاه، أو أكمل عدّ كل كاشير في قسم «النقدية حسب الكاشير» أدناه، أو اشرح سبب الفارق في الملاحظة أدناه للمتابعة.",
    varianceNoteLabel:"توضيح الفارق (مطلوب أثناء عدم التطابق):",
    varianceNotePh:"مثال: «تقرير إغلاق جهاز فيزا 2 مفقود — يُتابع مع FDM صباحاً»",
    productionIntro:"راجع أرقام مؤشر الإنتاجية لهذا الأسبوع قبل الاعتماد — انخفاض عدد تسجيلات الوصول/المغادرة لموظف متخصص قد يكون بسبب مكالمات المجاملة/المغادرة.",
    goToProduction:"مراجعة مؤشر الإنتاجية ←",
    confirmProduction:"تأكيد مراجعة مؤشر الإنتاجية",
    productionConfirmedBy:"أكّد مؤشر الإنتاجية ",
    stepsIncompleteToast:"أكمل هذه الخطوات أولاً: {0}",
    closeIntro:"هذه نقطة الاعتماد النهائي — تقابل لحظة اكتمال تدقيق أوبرا الليلي الفعلي وتغيير المدقق لتاريخ العمل. أغلق فقط بعد حدوث ذلك فعلياً؛ يبقى التدقيق مفتوحاً وقابلاً للتعديل بحالة «معتمد» حتى ذلك الحين.",
    closingBusinessDate:"تاريخ العمل الذي يُغلق:",
    newBusinessDateLabel:"تاريخ العمل الجديد (بعد الترحيل):",
    closeAndConfirm:"إغلاق وتأكيد",
    closedByLabel:"أُغلق بواسطة ",
    closedRolledTo:"هذا التدقيق مُغلق ونهائي — تم ترحيل تاريخ العمل إلى {0}.",
    closeSignatureNote:"سيُدخل رمزه في الخطوة التالية، كتوقيع — يمكن أن يكون مدير مناوبة ليلية مختلفاً عن الخطوة 5.",
    multiDateTitle:"عدة تواريخ عمل في هذا الملف",
    multiDateBody:"يشمل هذا الملف {0} تواريخ عمل مختلفة — على الأرجح تشغيل تعويضي بعد ليلة فائتة. سيتابع هذا التدقيق ويُغلق باعتباره {1}؛ عالج التاريخ (التواريخ) الأخرى في رفعة منفصلة بعد إغلاق هذا التدقيق.",
    gapsTitle:"تدقيق مُغلق مفقود",
    gapsBody:"لم يُعثر على تدقيق مُغلق لـ: {0} — تحقق من ذلك قبل اعتبار هذا التشغيل مكتملاً (قد لا يكون تاريخ العمل قد تقدّم، أو فاتت ليلة تدقيق).",

    /* ── BRIEF-NIGHT-AUDIT-2 المرحلة N2 — مطابقة المدفوعات. مصطلحات
       مقترحة، بحاجة لمراجعة خالد (LANGUAGE.md). ── */
    stepCashPerCashier:"النقدية حسب الكاشير",
    stepNonCardSettlements:"تسويات بدون بطاقة",
    cashCountedOf:"تم عدّ {0} من أصل {1} كاشير{2}",
    cashReconciledNote:"تم عدّ جميع الكاشيرين، والفروقات ضمن الحد المسموح.",
    cashNotReconciledNote:"لم يُعدّ بعض الكاشيرين بعد، أو أن الفارق يتجاوز الحد المسموح.",
    goToCash:"الانتقال إلى تبويب النقدي ←",
    nonCardIntro:"تُسوَّى هذه البنود مباشرة — لا يوجد جهاز طرفي أو PLO لمطابقتها. تُعرض هنا لإظهار إجمالي الليلة الكامل، دون اشتراط مطابقة فارق.",
    totalSettled:"إجمالي المسدد (جميع طرق الدفع)",
    settledTxns:"{0} معاملة{1}"
  },
  reports:{
    emptyUpload:"ارفع ملف أوبرا أولاً.",
    draftStamp:"— مسودة —", draftStampPlain:"مسودة",
    title:"تقرير التدقيق الليلي",
    businessDate:"تاريخ العمل: {0} · تاريخ الإنشاء: {1}",
    auditorLbl:"المدقق: ", nightMgrLbl:" · مدير المناوبة الليلية: ",
    balanced:"✓ متطابق", discrepancy:"⚠ فارق",
    cardRecon:"مطابقة البطاقات",
    card:"البطاقة", opera:"أوبرا", txns:"المعاملات", machines:"الأجهزة", machTxns:"معاملات الأجهزة",
    plo:"PLO", ploTxns:"معاملات PLO", discCol:"الفارق", status:"الحالة",
    ok:"سليم", amountCountOff:"فارق مبلغ وعدد", amountOff:"فارق مبلغ", countOff:"فارق عدد",
    total:"الإجمالي", balancedBadge:"متطابق", discrepancyBadge:"فارق",
    totalSettled:"إجمالي المسدد (جميع طرق الدفع)",
    cashDrop:"التحصيل النقدي",
    toleranceNote:"الفروقات ضمن {0} ريال تُعد تفاوتاً طبيعياً في التعامل والتقريب، وتظهر كـ«ضمن الهامش» وليست فارقاً حقيقياً.",
    agent:"الموظف", operaDrop:"تحصيل أوبرا", physicalCount:"العدّ الفعلي", variance:"الفارق",
    nonCardSettlements:"تسويات بدون بطاقة",
    nightAuditor:"المدقق الليلي", nightManager:"مدير المناوبة الليلية", dateTime:"التاريخ / الوقت",
    openFlagsAck:"إشارات مفتوحة تم الإقرار بها", none:"لا يوجد", itemsCount:"{0} عنصر",
    journalTitle:"التدقيق الليلي — اليومية النهائية",
    txCount:"{0} معاملة",
    date:"التاريخ", time:"الوقت", room:"الغرفة", guest:"النزيل", trx:"رقم المعاملة",
    description:"الوصف", cardRef:"البطاقة/المرجع", debit:"مدين", credit:"دائن",
    receipt:"الإيصال", st:"الحالة", comment:"ملاحظة",
    cashSubtotal:"مجموع النقدي — {0}", netDrop:"صافي التحصيل: {0} ريال",
    correctionsSummary:"ملخص التصحيحات",
    roomGuest:"غرفة {0} · {1}",
    selfCorrectedByAgent:"تصحيح ذاتي من الموظف", flaggedThenCorrected:"وضع المدقق إشارة ثم صُحّحت",
    original:"⚑ الأصل: ", reversal:"↩ العكس: ",
    openFlagsUnresolved:"إشارات مفتوحة (غير محلولة وقت إعداد التقرير)",
    tabSummary:"ملخص المطابقة", tabJournal:"تقرير اليومية النهائي",
    savePdf:"حفظ PDF", saveExcel:"حفظ Excel", print:"طباعة", exportJson:"تصدير JSON",
    footnote:"يجمع PDF/الطباعة كلا التقريرين؛ ملف Excel بيانات مُهيكلة عبر عدة أوراق (الملخص، اليومية، النقدي، PLO)",
    writtenToFolder:" · كُتب في مجلدك المتصل.", downloaded:" · تم التنزيل."
  },
  journal:{
    empty:"ارفع ملف أوبرا أولاً.",
    filterAll:"الكل ({0})", filterUnchecked:"غير محقَّق ({0})", filterPayments:"مدفوعات ({0})",
    filterCharges:"رسوم ({0})", filterCards:"بطاقات ({0})", filterCash:"نقدي ({0})",
    filterCorrections:"تصحيحات ({0})", filterPlo:"PLO ({0})",
    filterFlagged:"عليه إشارة ({0})", filterNew:"جديد ({0})",
    progress:"تقدّم اليومية", checkedOf:"{0}/{1} محقَّق", nFlagged:"{0} عليه إشارة",
    checkAll:"تحقّق من الكل", resync:"إعادة مزامنة",
    keysLegend:"المفاتيح: ",
    keyCheck:" تحقّق  ", keyFlag:" إشارة  ", keyNote:" ملاحظة  ", keyPlo:" PLO  ",
    keyLink:" ربط  ", keyPick:" اختيار من قائمة PLO/ربط مفتوحة  ",
    keyTab:" التالي غير المحقَّق  ", keyArrows:" تنقّل  ", keyEsc:" إغلاق  1–8 تصفية",
    date:"التاريخ", time:"الوقت", room:"الغرفة", guest:"النزيل", trx:"رقم المعاملة",
    description:"الوصف", cardRef:"البطاقة/المرجع", debit:"مدين", credit:"دائن",
    cashier:"الكاشير", user:"المستخدم", receipt:"الإيصال", plo:"PLO", flag:"إشارة",
    cash:"نقدي", cityLedger:"دفتر أستاذ النزلاء",
    corrTitle:"مبلغ سالب أو مرجع 'تصحيح' — تحقق من القيد الأصلي",
    corrBadge:"تصحيح",
    taxIncludes:"يشمل {0} بند ضريبة/رسم{1}: ",
    taxTotalIncl:" — الإجمالي شامل الضريبة: {0} ريال. التحقق من هذا الصف يحقق الجميع.",
    taxBadge:"+ضريبة", taxBadgeN:"+ضريبة ({0})",
    fxTitle:"دُفع بعملة {0} بقيمة {1} بسعر صرف {2} ← تم تحويله إلى {3} ريال للمطابقة. يجب أن يتوقع العدّ الفعلي نقداً بعملة {0} هنا، وليس ريالاً.",
    checkedTip:"محقَّق — انقر لإلغاء التحقق", flaggedTip:"عليه إشارة — انقر للتوسيع",
    verifyTip:"تحقق: النوع والمعاملة يطابقان الإيصال · المبلغ مطابق · معتمدة وليست مرفوضة — ثم انقر للتحقق",
    ploKeyTip:"المفتاح: P (ركّز على الصف ثم اضغط P)", ploLabel:"PLO",
    removePloTag:"إزالة وسم PLO",
    selfCorrected:"تصحيح ذاتي", corrected:"مصحَّح", unlink:"إلغاء الربط",
    linkedFrom:"مرتبط من ", addComment:"إضافة ملاحظة…",
    flagBtn:"إشارة",
    linkKeyTip:"اربط هذا بمعاملته المطابقة — للتصحيحات الذاتية الروتينية التي لا تحتاج إشارة. المفتاح: L (ركّز على الصف ثم اضغط L)",
    linkBtn:"ربط",
    describeWrong:"صف ما هو الخطأ:",
    flagPh:"مثال: «سُجّلت كفيزا، والإيصال يُظهر ماستركارد» أو «المبلغ يجب أن يكون 1501.21»",
    correctionLinked:"تم ربط التصحيح",
    suggestedMatches:"مطابقات مقترحة — انقر للربط:",
    score:"النتيجة {0}", confirmArrow:"تأكيد ←",
    enterReversalPrompt:"أدخل رقم معاملة العكس:", enterManually:"إدخال يدوي",
    clearFlag:"إزالة الإشارة", collapse:"طي",
    linkToMatch:"اربط هذا بمعاملته المطابقة — للتصحيح الذاتي الروتيني، دون حاجة لإشارة أو ملاحظة:",
    noObviousMatch:"لا توجد مطابقة واضحة في هذا الملف.",
    enterMatchingPrompt:"أدخل رقم المعاملة المطابقة:", cancel:"إلغاء", linkArrow:"ربط ←",
    noMatchFilter:"لا توجد معاملات تطابق هذه التصفية.",
    onChargeAbove:"ضمن الرسم أعلاه"
  },
  production:{
    noShiftFeedFolder:"لم يُعثر على مجلد بيانات المناوبات هناك — اختر مجلد سجلات الحضور (Records/Attendance/)، وتأكد أن الحضور زامن أسبوع جدول واحد على الأقل",
    loadedShiftHours:"تم تحميل ساعات المناوبة لـ {0} يوم-موظف{1} ✓",
    failedShiftFeed:"فشل قراءة بيانات المناوبات: {0}",
    useEdgeChrome:"استخدم متصفح إيدج أو كروم للوصول إلى المجلد",
    folderAccessFailed:"فشل الوصول إلى المجلد: {0}",
    expectedXml:"{0}: يُتوقَّع ملف XML لسجل النشاط",
    noActivityRecords:"{0}: لا توجد سجلات نشاط",
    newEventsLoaded:"{0}: تم تحميل {1} حدث جديد{2} (من أصل {3} في الملف)",
    fileError:"{0}: {1}",
    pickWeekFirst:"اختر أسبوعاً أولاً",
    savedFile:"تم حفظ {0} ✓", downloadedFile:"تم تنزيل {0} ✓",
    saveFailed:"فشل الحفظ: {0}",
    excelLibUnavailable:"مكتبة Excel غير متاحة", excelExportFailed:"فشل تصدير Excel: {0}",
    week:"الأسبوع", noHistoryYet:"لا يوجد أرشيف يومية أو سجل نشاط محمَّل بعد",
    exportExcel:"تصدير Excel", saveWeeklyRecord:"حفظ سجل الأسبوع", saving:"جارٍ الحفظ…",
    noFolderConnected:"لا يوجد مجلد متصل — سيقوم الزرّان أعلاه بالتنزيل إلى متصفحك بدلاً من ذلك. ",
    connectFromUpload:"اربط مجلداً من شاشة الرفع للحفظ مباشرة في مجلد سجلاتك.",
    checkInOutLog:"سجل تسجيل الوصول / المغادرة",
    eventsLoaded:"{0} حدث{1} محمَّل عبر كل الأسابيع. ",
    exportsFiltered:"غالباً ما تكون ملفات أوبرا مُصفّاة لنوع إجراء واحد — ارفع ملفات الوصول والمغادرة بشكل منفصل، وسيتم دمجها تلقائياً.",
    uploadActivityXml:"رفع ملف XML لسجل النشاط",
    rosterLink:"ربط جدول المناوبات (الحضور)",
    connectedShiftHours:"متصل: {0}. ",
    shiftHoursLoaded:"تم تحميل ساعات المناوبة لـ {0} أسبوع{1}.",
    noShiftHoursYet:"لم تُحمَّل ساعات مناوبة بعد — انقر تحديث.",
    connectAttendanceDesc:"اربط مجلد سجلات الحضور لتطبيع الإنتاجية حسب ساعات العمل الفعلية، بدلاً من عدد أسبوعي خام. اختياري — كل ما سبق يعمل بدونه.",
    refresh:"تحديث", loadingEllipsis:"جارٍ التحميل…",
    connectAttendanceFolder:"ربط مجلد الحضور", reconnect:"إعادة الربط",
    guestCareLink:"ربط بوابة النزلاء (اتصالات النزلاء)",
    connectedCallEvents:"متصل عبر مجلد النظام المشترك. ",
    callEventsLoaded:"تم تحميل اتصالات النزلاء لـ {0} يوم{1}.",
    noCallEventsYet:"لم تُحمَّل اتصالات نزلاء بعد — انقر تحديث.",
    connectGuestCareDesc:"اربط مجلد النظام المشترك (تبويب الموظفون والرموز) لاحتساب اتصالات المجاملة والمغادرة من بوابة النزلاء ضمن وحدات حجم الإنتاجية — بحيث لا يتأثر موظف مكلَّف بالاتصالات رغم قلة عمليات تسجيل الوصول/المغادرة لديه. اختياري — كل ما سبق يعمل بدونه.",
    failedCallEvents:"فشل قراءة اتصالات النزلاء: {0}",
    courtesyCalls:"اتصالات المجاملة", departureCalls:"اتصالات المغادرة",
    ptsPerCourtesyCall:"نقاط / اتصال مجاملة", ptsPerDepartureCall:"نقاط / اتصال مغادرة",
    dashboard:"لوحة المؤشرات",
    mapStaffFirst:"اربط موظفاً واحداً على الأقل أدناه لعرض اللوحة.",
    leaderboard1:"المركز الأول (للعرض فقط)", scorePct:"{0}% نتيجة",
    teamAccuracy:"متوسط دقة الفريق", totalUnits:"إجمالي الوحدات",
    fairShare:"الحصة العادلة (100% ÷ عدد الموظفين)", mappedStaff:"الموظفون المربوطون",
    scoreByStaff:"النتيجة حسب الموظف", volumeBreakdown:"تفصيل حجم العمل",
    scoreTrend:"اتجاه النتيجة — آخر {0} أسبوع{1}",
    detail:"التفاصيل",
    rankTip:"ترتيب لوحة الصدارة — للعرض فقط، ليس جزءاً من النتيجة", rank:"الترتيب",
    staff:"الموظف", id:"الرقم", staffIdCol:"رقم الموظف", journalTx:"معاملات اليومية", checkIns:"تسجيل الوصول", checkOuts:"تسجيل المغادرة",
    units:"الوحدات", volumeModel:"نموذج الحجم", hrsMetOnDuty:"ساعات محقَّقة/ساعات عمل",
    dutyHrsTip:"من ربط جدول المناوبات (الحضور)، إن كان متصلاً", dutyHrs:"ساعات العمل",
    coverageTip:"ساعات العمل التي كانت فيها حصة هذا الشخص من نشاط تلك الساعة مساوية أو أعلى من حصته المتوقعة، حسب عدد الزملاء العاملين في نفس الساعة",
    coverage:"التغطية",
    flaggedHrsTip:"ساعات العمل التي تجاوزت فيها حصة هذا الشخص هامش التنبيه — انظر إعدادات التقييم",
    flaggedHrs:"ساعات متجاوزة", corrections:"التصحيحات", accuracy:"الدقة", score:"النتيجة",
    noMappedStaff:"لا يوجد موظفون مربوطون بعد — أضف إدخالات في ربط الموظفين أدناه.",
    noEmployeeIdTip:"لا يوجد رقم موظف — لن يُربط مع مؤشرات الأداء الأخرى", missing:"غير موجود",
    noAttendanceFallback:"لا توجد ساعات من جدول المناوبات هذا الأسبوع — تم الرجوع لحصة إجمالي وحدات الفريق",
    fallbackPct:"احتياطي {0}%",
    hrsMet:"{0}/{1} ساعة",
    flaggedHoursTip:"تجاوز هامش التنبيه في هذا العدد من ساعات العمل",
    coverageFootnote:"التغطية = ساعات العمل التي حقق فيها هذا الشخص حصته المتوقعة أو تجاوزها (100% ÷ الزملاء العاملين في تلك الساعة)، من ربط الحضور. ",
    scoreFootnote:"النتيجة = {0}% × نتيجة الحجم + {1}% × نتيجة الدقة (كل منها محسوبة حد أدنى←مستهدف←تفوّق، والترتيب للعرض فقط). ",
    fallbackNote:"الصفوف المُعلَّمة بـ«احتياطي» ليس لها ساعات حضور هذا الأسبوع، وتستخدم نموذج الحصة العادلة للفريق بدلاً من ذلك (الحصة العادلة هذا الأسبوع: {0}%، إجمالي وحدات الفريق: {1}).",
    connectForHourly:"اربط مجلد الحضور أعلاه لتفعيل نموذج التغطية الساعية — الجميع هنا على نموذج الحصة العادلة الاحتياطي (الحصة العادلة: {0}%، إجمالي وحدات الفريق: {1}).",
    unmappedTitle:"هويات غير مربوطة هذا الأسبوع — مستبعدة من الاحتساب حتى تُربط",
    unmappedAgents:"أرقام الكاشير (اليومية)", unmappedUsers:"أسماء مستخدمي أوبرا (سجل النشاط)",
    assignTo:"إسناد {0} إلى:", chooseStaff:"اختر الموظف…", assign:"إسناد", cancel:"إلغاء",
    staffMapping:"ربط الموظفين",
    staffId:"رقم الموظف", name:"الاسم", cashierId:"رقم الكاشير", operaUsernames:"اسم مستخدم أوبرا",
    cashierIdPh:"مثال: 101", usernamePh:"HB4X1-AALDOSSARI@ACCOREN", clear:"مسح",
    noRegistryStaff:"لا يوجد موظفون في السجل المشترك بعد — اربط مجلد النظام من الموظفون والرموز.",
    scoringSettings:"إعدادات التقييم",
    weights:"الأوزان", volumeWeight:"وزن الحجم %", accuracyWeight:"وزن الدقة %",
    ptsPerTx:"نقاط / معاملة يومية", ptsPerCheckIn:"نقاط / تسجيل وصول", ptsPerCheckOut:"نقاط / تسجيل مغادرة",
    hourlyModelTitle:"نموذج التغطية الساعية (الأساسي — يتطلب ربط الحضور أعلاه)",
    flagMargin:"هامش التنبيه ×", bonusPerFlag:"نقاط إضافية / ساعة متجاوزة",
    thresholdPct:"الحد الأدنى %", targetPct:"المستهدف %", stretchPct:"التفوّق %",
    hourlyExplain:"لكل ساعة كان فيها الموظف المربوط على رأس العمل (حسب جدول مناوبات الحضور)، تُقارن حصته من نشاط تلك الساعة بحصته المتوقعة (100% ÷ الزملاء العاملين في تلك الساعة). «التغطية» = نسبة ساعات العمل التي حقق فيها حصته المتوقعة أو تجاوزها. الساعة التي تتجاوز فيها حصته {0}× حصته المتوقعة تُعلَّم كـ«متجاوزة» وتضيف {1} نقطة إضافية. مقياس الحجم = نسبة التغطية + (الساعات المتجاوزة × النقاط الإضافية)، ويُحتسب مقابل الحد الأدنى/المستهدف/التفوّق أعلاه. من ليس لديه أي ساعة عمل هذا الأسبوع (ربط الحضور غير متصل، أو لم يُربط بعد) يُحتسب على نموذج الحصة العادلة للفريق أدناه.",
    fallbackTitle:"الاحتياطي: الحد الأدنى/المستهدف/التفوّق كحصة عادلة للفريق (× الحصة العادلة — يتكيّف تلقائياً مع حجم الفريق)",
    thresholdX:"الحد الأدنى ×", targetX:"المستهدف ×", stretchX:"التفوّق ×",
    thisWeeksTts:"= الحد الأدنى/المستهدف/التفوّق لهذا الأسبوع",
    accuracyTitle:"الحد الأدنى/المستهدف/التفوّق للدقة (%)",
    finalExplain:"نسبة الحجم الاحتياطية (تُستخدم فقط بدون ربط الحضور) = وحدات الموظف ÷ إجمالي وحدات الفريق هذا الأسبوع، وتُحتسب من الحد الأدنى (0%) ← المستهدف (100%) ← مكافأة مقيدة حتى 110% عند التفوّق — بلا درجات متقطعة أبداً. الحد الأدنى/المستهدف/التفوّق مضاعفات من الحصة العادلة للفريق (100% ÷ الموظفين المربوطين)، وتتكيّف تلقائياً مع انضمام أو مغادرة الموظفين. الدقة = 1 − التصحيحات ÷ معاملات اليومية الخاصة، وتُحتسب بنفس الطريقة مقابل حدّها الأدنى/مستهدفها/تفوّقها الخاص. النتيجة النهائية = مزيج موزون من نتيجة الحجم (الاحتياطية أو الساعية) ونتيجة الدقة (وليس النسب الخام)",
    finalExplainWeighted:" (يعادل حالياً {0}% حجم / {1}% دقة)",
    finalExplainEnd:". الترتيب (موضع لوحة الصدارة) للعرض فقط — لا يدخل أبداً في احتساب النتيجة. التغييرات تُطبَّق فوراً وتُحفظ."
  },
  status:{draft:"مسودة",submitted:"مُرسل للمراجعة",approved:"معتمد",closed:"مُغلق"},
  xlsx:{
    businessDateLabel:"تاريخ العمل", cardBalance:"تطابق البطاقات", offBySar:"فارق {0} ريال",
    countBalance:"تطابق العدد", offByTxn:"فارق {0} معاملة", submittedLabel:"تاريخ الإرسال",
    approvedLabel:"تاريخ الاعتماد", ok:"سليم",
    hdrCard:"البطاقة", hdrOperaSar:"أوبرا (ريال)", hdrOperaTxns:"معاملات أوبرا",
    hdrMachSar:"إغلاق الجهاز (ريال)", hdrMachTxns:"معاملات الجهاز", hdrPloSar:"PLO (ريال)", hdrPloTxns:"معاملات PLO",
    hdrAmtDiscSar:"فارق المبلغ (ريال)", hdrCountDisc:"فارق العدد",
    nonCardSettlements:"تسويات بدون بطاقة",
    totalSettledSar:"إجمالي المسدد (ريال)", totalSettledTxns:"عدد معاملات الإجمالي المسدد",
    totalsSection:"الإجماليات", totalCashSar:"إجمالي النقدي (ريال)",
    trxNo:"رقم المعاملة", code:"الرمز", cashierId:"رقم الكاشير", cashier:"الكاشير", user:"المستخدم",
    operaRef:"مرجع أوبرا", trxType:"نوع المعاملة",
    fxCurrency:"عملة الصرف", fxFaceAmt:"المبلغ الأصلي", fxRate:"سعر الصرف",
    ploType:"نوع PLO", comment:"ملاحظة", correctionLink:"رابط التصحيح", linkedAt:"وقت الربط",
    txTypeTax:"ضريبة", txTypeCorrection:"تصحيح", txTypeCard:"دفعة بطاقة", txTypeCash:"نقدي",
    txTypeCL:"دفتر أستاذ النزلاء", txTypeReward:"نقاط مكافآت", txTypeCharge:"رسم", txTypeOTA:"تسوية عبر منصة حجز (OTA)",
    correctedBy:"صُحح بواسطة {0}", reversalOf:"عكس للمعاملة {0}",
    cashTxns:"معاملات نقدية", operaDebitSar:"مدين أوبرا (ريال)", operaCreditSar:"دائن أوبرا (ريال)",
    operaDropSar:"تحصيل أوبرا (ريال)", physicalCountSar:"العدّ الفعلي (ريال)", varianceSar:"الفارق (ريال)",
    pctOfNightDrop:"% من تحصيل الليلة",
    machine:"الجهاز", sarSuffix:" (ريال)", txnsSuffix:" (معاملات)",
    machineTotalSar:"إجمالي الجهاز (ريال)", machineTotalTxns:"إجمالي الجهاز (معاملات)",
    grandTotal:"الإجمالي الكلي", txnCountsHeader:"── عدد المعاملات ──",
    cardRefMasked:"البطاقة/المرجع (مُخفى)", amountSar:"المبلغ (ريال)",
    resolvedCorrections:"التصحيحات المحلولة", origTrx:"رقم المعاملة الأصلية",
    originalDescription:"الوصف الأصلي", origAmtSar:"المبلغ الأصلي (ريال)",
    revTrx:"رقم معاملة العكس", revDate:"تاريخ العكس", revCashier:"كاشير العكس",
    reversalDescription:"وصف العكس", revAmtSar:"مبلغ العكس (ريال)", source:"المصدر",
    selfCorrectedLabel:"تصحيح ذاتي", flaggedThenCorrectedLabel:"وُضعت إشارة ثم صُححت",
    openFlagsUnresolvedLabel:"إشارات مفتوحة (غير محلولة)", creditSar:"دائن (ريال)", debitSar:"مدين (ريال)",
    noCommentLower:"لا توجد ملاحظة"
  },
  identity:{
    loadingStaff:"جارٍ التحميل…",
    whoIsUsing:"من يستخدم {0}؟",
    enterIdThenPin:"أدخل رقمك الوظيفي، ثم رمزك التعريفي المكوّن من 4 أرقام.",
    resumeFolderAccess:"استئناف الوصول إلى المجلد",
    idFieldLabel:"الرقم الوظيفي", continueBtn:"متابعة", continueUnattributed:"المتابعة دون تسجيل الدخول (استخدام مشترك)",
    locked:"مقفل",
    unattributedName:"المكتب الأمامي (بدون نسب)",
    firstTimeConfirm:"أدخله مرة أخرى للتأكيد", firstTimeChoose:"أول مرة — اختر رمزاً من 4 أرقام",
    enterYourPin:"أدخل الرمز المكوّن من 4 أرقام",
    lockedHelp:"مقفل بعد 5 محاولات خاطئة — اطلب من مدير المناوبة الليلية إعادة تعيينه.",
    notYouBack:"لست أنت؟ رجوع",
    didntMatch:"لم يتطابق — حاول مجدداً من البداية.",
    pinTooEasy:"هذا الرمز سهل التخمين — اختر رمزاً آخر.",
    couldntSetPin:"تعذّر ضبط الرمز — حاول مجدداً.",
    unknownId:"هذا الرقم الوظيفي غير معروف.",
    notSynced:"لم تتم مزامنة قائمة الموظفين في هذا التطبيق بعد — اتصل بمجلد النظام أو تواصل مع مدير المناوبة الليلية.",
    inactive:"هذا الرقم الوظيفي لم يعد نشطاً.",
    noPinYet:"لم يتم تعيين رمز تعريفي لهذا الرقم بعد — اطلب من مدير المناوبة الليلية تعيينه.",
    lockedTryReset:"مقفل بعد 5 محاولات خاطئة — اطلب من مدير المناوبة الليلية إعادة تعيينه.",
    wrongPin:"رمز خاطئ — حاول مجدداً.",
    cantIdentify:"تعذّر تسجيل الدخول — اطلب المساعدة من مدير المناوبة الليلية.",
    signOffTitle:"اعتماد مدير المناوبة الليلية",
    noNightManager:"لا يوجد مدير مناوبة ليلية أو مدير النظام بعد — اطلب من مدير النظام منح صلاحية مدير المناوبة الليلية من الموظفون والرموز.",
    whoIsApproving:"من يعتمد هذا التدقيق؟",
    signAs:"التوقيع باسم {0}",
    lockedFivePins:"مقفل بعد 5 محاولات خاطئة.",
    cantSignOff:"لا يمكن الاعتماد هنا.",
    resetPinTitle:"إعادة تعيين الرمز — {0}", setPinTitle:"إعداد الرمز — {0}",
    handKeyboard:"سلّم لوحة المفاتيح لـ {0} — {1}",
    confirmOnceMore:"أكّد مرة أخرى.", chooseFourDigit:"اختر رمزاً من 4 أرقام.",
    didntMatchStart:"لم يتطابق — ابدأ من جديد.",
    tooEasyPick:"سهل التخمين — اختر رمزاً آخر.", couldntSetPin2:"تعذّر ضبط الرمز.",
    folderAccessFailedChrome:"فشل الوصول إلى المجلد — استخدم متصفح كروم أو إيدج",
    sharedRegistry:"سجل الموظفين المشترك",
    connectedSync:"متصل: {0} — الرموز والصلاحيات تتزامن مع كل تطبيقات النظام.",
    notConnected:"غير متصل — الرموز تعمل على هذا الجهاز فقط حتى تربط مجلد النظام المشترك (نفس المجلد الرئيسي الذي تتصل به رعاية النزلاء).",
    filesProtocolMsg:"ربط المجلد يحتاج الخادم المحلي — افتح التطبيق عبر \"Open PMS Apps.bat\"، وليس بالنقر المزدوج على هذا الملف.",
    connectPmsFolder:"ربط مجلد النظام", reconnectPmsFolder:"إعادة ربط مجلد النظام",
    settings:"الإعدادات", idleTimeout:"مهلة الخمول (بالدقائق)",
    allowUnattributed:"السماح بشاشة «المكتب الأمامي (بدون نسب)»",
    staffCount:"الموظفون ({0})",
    name:"الاسم", position:"المسمى الوظيفي", status:"الحالة", pin:"الرمز", roleCol:"صلاحية التدقيق الليلي",
    active:"نشط", inactive:"غير نشط",
    resetPinBtn:"إعادة تعيين الرمز", setPinBtn:"إعداد الرمز",
    viewer:"مطّلع", topAdminBadge:"مدير النظام",
    roleAuditor:"مدقق", roleNightManager:"مدير المناوبة الليلية",
    permissionsMatrix:"جدول الصلاحيات — الشاشات التي تظهر لكل صلاحية",
    externalCount:"خارجي ({0})", addExternalMember:"+ إضافة عضو خارجي",
    externalDesc:"أشخاص من خارج المكتب الأمامي (مثل مقيّم) — مستبعدون من نتائج الإنتاجية وكل التصادير؛ يظهرون في شاشة تسجيل الدخول لهذا التطبيق فقط بعد منحهم صلاحية هنا.",
    noExternalYet:"لا يوجد أعضاء خارجيون بعد.",
    positionDept:"المسمى / القسم",
    addExternalTitle:"إضافة عضو خارجي",
    nameLabel:"الاسم", idLabel:"الرقم",
    displayNameOptional:"الاسم الظاهر (اختياري — يستخدم الاسم افتراضياً)",
    positionLabel:"المسمى الوظيفي", departmentOptional:"القسم (اختياري)",
    add:"إضافة",
    editTitle:"تعديل — {0}", displayNameLabel:"الاسم الظاهر", departmentLabel:"القسم",
    requiredNameIdPos:"الاسم والرقم والمسمى الوظيفي مطلوبة.",
    idInUse:"هذا الرقم مستخدَم بالفعل — عدّله.",
    idMustStartExt:"يجب أن يبدأ الرقم بـ \"ext-\".", couldntAddPerson:"تعذّرت إضافة هذا الشخص.",
    requiredNameDisplayPos:"الاسم والاسم الظاهر والمسمى الوظيفي مطلوبة.",
    couldntSaveChanges:"تعذّر حفظ التغييرات.",
    activityTitle:"العمليات — {0} من {1} (هذا الجهاز)",
    everyone:"الجميع", allActions:"كل العمليات", to:"إلى",
    nothingLogged:"لا يوجد شيء مسجَّل بعد.",
    when:"الوقت", who:"من", action:"العملية", target:"الهدف", detail:"التفاصيل"
  }
}
};
